export const marketData = {
    "Blocs": [
        {fr: "Terre", buyPrice: 5, img: "../images/blocks/dirt.png"},
        {fr: "Mycélium", buyPrice: 5, img: "../images/blocks/mycelium.png"},
        {fr: "Terre stérile", buyPrice: 5, img: "../images/blocks/coarse_dirt.png"},
        {fr: "Podzol", buyPrice: 5, img: "../images/blocks/podzol.png"},
        {fr: "Sable", buyPrice: 15, img: "../images/blocks/sand.png"},
        {fr: "Grès", buyPrice: 15, img: "../images/blocks/sandstone.png"},
        {fr: "Grès taillé", buyPrice: 15, img: "../images/blocks/cut_sandstone.png"},
        {fr: "Sable rouge", buyPrice: 15, img: "../images/blocks/red_sand.png"},
        {fr: "Grès rouge", buyPrice: 15, img: "../images/blocks/red_sandstone.png"},
        {fr: "Grès rouge taillé", buyPrice: 15, img: "../images/blocks/cut_red_sandstone.png"},
        {fr: "Roche", buyPrice: 15, img: "../images/blocks/stone.png"},
        {fr: "Briques de pierre", buyPrice: 15, img: "../images/blocks/stone_bricks.png"},
        {fr: "Briques de pierre moussues", buyPrice: 15, img: "../images/blocks/mossy_stone_bricks.png"},
        {fr: "Briques de pierre craquelées", buyPrice: 15, img: "../images/blocks/cracked_stone_bricks.png"},
        {fr: "Briques de pierre sculptées", buyPrice: 15, img: "../images/blocks/chiseled_stone_bricks.png"},
        {fr: "Pierre", buyPrice: 15, img: "../images/blocks/cobblestone.png"},
        {fr: "Pierre moussue", buyPrice: 15, img: "../images/blocks/mossy_cobblestone.png"},
        {fr: "Gravier", buyPrice: 15, img: "../images/blocks/gravel.png"},
        {fr: "Granite", buyPrice: 15, img: "../images/blocks/granite.png"},
        {fr: "Diorite", buyPrice: 15, img: "../images/blocks/diorite.png"},
        {fr: "Andésite", buyPrice: 15, img: "../images/blocks/andesite.png"},
        {fr: "Granite poli", buyPrice: 15, img: "../images/blocks/polished_granite.png"},
        {fr: "Diorite polie", buyPrice: 15, img: "../images/blocks/polished_diorite.png"},
        {fr: "Andésite polie", buyPrice: 15, img: "../images/blocks/polished_andesite.png"},
        {fr: "Obsidienne", buyPrice: 500, img: "../images/blocks/obsidian.png"},
        {fr: "Planches de chêne", buyPrice: 15, img: "../images/blocks/oak_planks.png"},
        {fr: "Planches de sapin", buyPrice: 15, img: "../images/blocks/spruce_planks.png"},
        {fr: "Planches de bouleau", buyPrice: 15, img: "../images/blocks/birch_planks.png"},
        {fr: "Planches d'acacia", buyPrice: 15, img: "../images/blocks/acacia_planks.png"},
        {fr: "Planches d'acajou", buyPrice: 15, img: "../images/blocks/jungle_planks.png"},
        {fr: "Planches de chêne noir", buyPrice: 15, img: "../images/blocks/dark_oak_planks.png"},
        {fr: "Bloc de Slime", buyPrice: 15, img: "../images/blocks/slime_block.png"}
    ],
    "Items": [
        {fr: "Flèche", buyPrice: 10, img: "../images/items/arrow.png"},
        {fr: "Torche", buyPrice: 3, img: "../images/items/torch.png"},
        {fr: "Perle de l'Ender", buyPrice: 1500, img: "../images/items/ender_pearl.png"},
        {fr: "Barre de l'End", buyPrice: 175, img: "../images/items/end_rod.png"},
        {fr: "Potion de soin volatile", buyPrice: 1500, img: "../images/items/splash_potion.png"},
        {fr: "Table de craft", buyPrice: 100, img: "../images/blocks/crafting_table.png"},
        {fr: "Table d'enchantement", buyPrice: 1000, img: "../images/blocks/enchanting_table.png"},
        {fr: "Enclume", buyPrice: 1000, img: "../images/blocks/anvil.png"},
        {fr: "Coffre de l'Ender", buyPrice: 800, img: "../images/blocks/ender_chest.png"},
        {fr: "Coffre", buyPrice: 100, img: "../images/blocks/chest.png"},
        {fr: "Lit", buyPrice: 100, img: "../images/items/red_bed.png"},
        {fr: "Four", buyPrice: 100, img: "../images/blocks/furnace.png"},
        {fr: "Jukebox", buyPrice: 1000, img: "../images/blocks/jukebox.png"}
    ],
    "Minerais": [
        {fr: "Argile", buyPrice: 15, img: "../images/items/clay_ball.png"},
        {fr: "Silex", buyPrice: 15, img: "../images/items/flint.png"},
        {fr: "Charbon", buyPrice: 200, img: "../images/items/coal.png"},
        {fr: "Lingot de fer", buyPrice: 200, img: "../images/items/iron_ingot.png"},
        {fr: "Lingot d'or", buyPrice: 500, img: "../images/items/gold_ingot.png"},
        {fr: "Poussière de Redstone", buyPrice: 50, img: "../images/items/redstone.png"},
        {fr: "Diamant", buyPrice: 500, img: "../images/items/diamond.png"},
        {fr: "Minerai de charbon", buyPrice: 200, img: "../images/blocks/coal_ore.png"},
        {fr: "Minerai de fer", buyPrice: 200, img: "../images/blocks/iron_ore.png"},
        {fr: "Minerai d'or", buyPrice: 500, img: "../images/blocks/gold_ore.png"},
        {fr: "Minerai de Redstone", buyPrice: 450, img: "../images/blocks/redstone_ore.png"},
        {fr: "Minerai de diamant", buyPrice: 1000, img: "../images/blocks/diamond_ore.png"},
        {fr: "Minerai d'Histerite", buyPrice: 10000, img: "https://placehold.co/128x128/2c2c2c/e74c3c?text=Histerite+Ore"},
        {fr: "Minerai Aléatoire", buyPrice: 20000, img: "https://placehold.co/128x128/2c2c2c/e74c3c?text=Random+Ore"},
        {fr: "Bloc de charbon", buyPrice: 1800, img: "../images/blocks/coal_block.png"},
        {fr: "Bloc de fer", buyPrice: 1800, img: "../images/blocks/iron_block.png"},
        {fr: "Bloc d'or", buyPrice: 4500, img: "../images/blocks/gold_block.png"},
        {fr: "Bloc de Redstone", buyPrice: 450, img: "../images/blocks/redstone_block.png"},
        {fr: "Bloc de diamant", buyPrice: 9000, img: "../images/blocks/diamond_block.png"},
        {fr: "Bloc d'Histerite", buyPrice: 90000, img: "https://placehold.co/128x128/2c2c2c/e74c3c?text=Histerite+Block"}
    ],
    "Nature": [
        {fr: "Bois d'acacia", buyPrice: 50, img: "../images/blocks/acacia_wood.png"},
        {fr: "Bois d'acajou", buyPrice: 50, img: "../images/blocks/jungle_wood.png"},
        {fr: "Bois de bouleau", buyPrice: 50, img: "../images/blocks/birch_wood.png"},
        {fr: "Bois de chêne", buyPrice: 50, img: "../images/blocks/oak_wood.png"},
        {fr: "Bois de chêne noir", buyPrice: 50, img: "../images/blocks/dark_oak_wood.png"},
        {fr: "Bois de sapin", buyPrice: 50, img: "../images/blocks/spruce_wood.png"},
        {fr: "Steak", buyPrice: 50, img: "../images/items/cooked_beef.png"},
        {fr: "Cactus", buyPrice: 500, img: "../images/blocks/cactus.png"},
        {fr: "Bûche d'acacia", buyPrice: 50, img: "../images/blocks/acacia_log.png"},
        {fr: "Bûche d'acajou", buyPrice: 50, img: "../images/blocks/jungle_log.png"},
        {fr: "Bûche de bouleau", buyPrice: 50, img: "../images/blocks/birch_log.png"},
        {fr: "Bûche de chêne", buyPrice: 50, img: "../images/blocks/oak_log.png"},
        {fr: "Bûche de chêne noir", buyPrice: 50, img: "../images/blocks/dark_oak_log.png"},
        {fr: "Bûche de sapin", buyPrice: 50, img: "../images/blocks/spruce_log.png"},
        {fr: "Citrouille", buyPrice: 225, img: "../images/blocks/pumpkin.png"},
        {fr: "Melon", buyPrice: 225, img: "../images/items/melon_slice.png"},
        {fr: "Bûche d'acacia écorcée", buyPrice: 50, img: "../images/blocks/stripped_acacia_log.png"},
        {fr: "Bûche d'acajou écorcée", buyPrice: 50, img: "../images/blocks/stripped_jungle_log.png"},
        {fr: "Bûche de bouleau écorcée", buyPrice: 50, img: "../images/blocks/stripped_birch_log.png"},
        {fr: "Bûche de chêne écorcée", buyPrice: 50, img: "../images/blocks/stripped_oak_log.png"},
        {fr: "Bûche de chêne noir écorcée", buyPrice: 50, img: "../images/blocks/stripped_dark_oak_log.png"},
        {fr: "Bûche de sapin écorcée", buyPrice: 50, img: "../images/blocks/stripped_spruce_log.png"},
        {fr: "Pomme de terre", buyPrice: 50, img: "../images/items/potato.png"},
        {fr: "Betterave", buyPrice: 50, img: "../images/items/beetroot.png"},
        {fr: "Pousse d'acacia", buyPrice: 100, img: "../images/blocks/acacia_sapling.png"},
        {fr: "Pousse d'acajou", buyPrice: 100, img: "../images/blocks/jungle_sapling.png"},
        {fr: "Pousse de bouleau", buyPrice: 100, img: "../images/blocks/birch_sapling.png"},
        {fr: "Pousse de chêne", buyPrice: 100, img: "../images/blocks/oak_sapling.png"},
        {fr: "Pousse de chêne noir", buyPrice: 100, img: "../images/blocks/dark_oak_sapling.png"},
        {fr: "Pousse de sapin", buyPrice: 100, img: "../images/blocks/spruce_sapling.png"},
        {fr: "Carotte", buyPrice: 50, img: "../images/items/carrot.png"},
        {fr: "Blé", buyPrice: 50, img: "../images/items/wheat.png"},
        {fr: "Feuilles d'acacia", buyPrice: 20, img: "../images/blocks/acacia_leaves.png"},
        {fr: "Feuilles d'acajou", buyPrice: 20, img: "../images/blocks/jungle_leaves.png"},
        {fr: "Feuilles de bouleau", buyPrice: 20, img: "../images/blocks/birch_leaves.png"},
        {fr: "Feuilles de chêne", buyPrice: 20, img: "../images/blocks/oak_leaves.png"},
        {fr: "Feuilles de chêne noir", buyPrice: 20, img: "../images/blocks/dark_oak_leaves.png"},
        {fr: "Feuilles de sapin", buyPrice: 20, img: "../images/blocks/spruce_leaves.png"},
        {fr: "Graines", buyPrice: 10, img: "../images/items/wheat_seeds.png"},
        {fr: "Pomme", buyPrice: 100, img: "../images/items/apple.png"},
        {fr: "Poudre d'os", buyPrice: 100, img: "../images/items/bone_meal.png"},
        {fr: "Bloc d'herbe", buyPrice: 200, img: "../images/blocks/grass_block.png"},
        {fr: "Liane", buyPrice: 200, img: "../images/blocks/vine.png"},
        {fr: "Canne à sucre", buyPrice: 200, img: "../images/items/sugar_cane.png"},
        {fr: "Champignon rouge", buyPrice: 200, img: "../images/blocks/red_mushroom.png"},
        {fr: "Champignon brun", buyPrice: 200, img: "../images/blocks/brown_mushroom.png"},
        {fr: "Bloc de champignon rouge", buyPrice: 1800, img: "../images/blocks/red_mushroom_block.png"},
        {fr: "Bloc de champignon brun", buyPrice: 1800, img: "../images/blocks/brown_mushroom_block.png"},
        {fr: "Gâteau", buyPrice: 100, img: "../images/items/cake.png"},
        {fr: "Herbes hautes", buyPrice: 100, img: "../images/blocks/grass.png"},
        {fr: "Fougère", buyPrice: 100, img: "../images/blocks/fern.png"},
        {fr: "Grande fougère", buyPrice: 100, img: "../images/blocks/large_fern.png"},
        {fr: "Arbuste mort", buyPrice: 100, img: "../images/blocks/dead_bush.png"},
        {fr: "Citrouille sculptée", buyPrice: 100, img: "../images/blocks/carved_pumpkin.png"},
        {fr: "Tige de champignon", buyPrice: 100, img: "../images/blocks/mushroom_stem.png"},
        {fr: "Pissenlit", buyPrice: 100, img: "../images/blocks/dandelion.png"},
        {fr: "Coquelicot", buyPrice: 100, img: "../images/blocks/poppy.png"},
        {fr: "Orchidée bleue", buyPrice: 100, img: "../images/blocks/blue_orchid.png"},
        {fr: "Allium", buyPrice: 100, img: "../images/blocks/allium.png"},
        {fr: "Houstonie bleue", buyPrice: 100, img: "../images/blocks/azure_bluet.png"},
        {fr: "Tulipe rouge", buyPrice: 100, img: "../images/blocks/red_tulip.png"},
        {fr: "Tulipe orange", buyPrice: 100, img: "../images/blocks/orange_tulip.png"},
        {fr: "Tulipe blanche", buyPrice: 100, img: "../images/blocks/white_tulip.png"},
        {fr: "Tulipe rose", buyPrice: 100, img: "../images/blocks/pink_tulip.png"},
        {fr: "Marguerite", buyPrice: 100, img: "../images/blocks/oxeye_daisy.png"},
        {fr: "Bleuet", buyPrice: 100, img: "../images/blocks/cornflower.png"},
        {fr: "Lilas", buyPrice: 100, img: "../images/blocks/lilac.png"},
        {fr: "Tournesol", buyPrice: 100, img: "../images/blocks/sunflower.png"},
        {fr: "Rosier", buyPrice: 100, img: "../images/blocks/rose_bush.png"},
        {fr: "Pivoine", buyPrice: 100, img: "../images/blocks/peony.png"}
    ],
    "Objets Spéciaux": [
        {fr: "Chest Finder", buyPrice: 15000, img: "../images/items/compass.png"},
        {fr: "Fertilized Dirt", buyPrice: 200000, img: "../images/blocks/farmland.png"},
        {fr: "Histerite Apple", buyPrice: 200000, img: "../images/items/enchanted_golden_apple.png"},
        {fr: "Obsidian Breaker", buyPrice: 10000, img: "../images/items/netherite_pickaxe.png"},
        {fr: "Dynamite", buyPrice: 600, img: "../images/blocks/tnt.png"},
        {fr: "Sponger", buyPrice: 1000, img: "../images/blocks/sponge.png"},
        {fr: "Chest Explorer", buyPrice: 10000, img: "../images/items/spyglass.png"},
        {fr: "Hang Glider", buyPrice: 20000, img: "../images/items/elytra.png"}
    ],
    "Décoration": [
        {fr: "Terre cuite blanche", buyPrice: 50, img: "../images/blocks/white_terracotta.png"},
        {fr: "Terre cuite orange", buyPrice: 50, img: "../images/blocks/orange_terracotta.png"},
        {fr: "Terre cuite magenta", buyPrice: 50, img: "../images/blocks/magenta_terracotta.png"},
        {fr: "Terre cuite bleu clair", buyPrice: 50, img: "../images/blocks/light_blue_terracotta.png"},
        {fr: "Terre cuite jaune", buyPrice: 50, img: "../images/blocks/yellow_terracotta.png"},
        {fr: "Terre cuite citron vert", buyPrice: 50, img: "../images/blocks/lime_terracotta.png"},
        {fr: "Terre cuite rose", buyPrice: 50, img: "../images/blocks/pink_terracotta.png"},
        {fr: "Terre cuite grise", buyPrice: 50, img: "../images/blocks/gray_terracotta.png"},
        {fr: "Terre cuite gris clair", buyPrice: 50, img: "../images/blocks/light_gray_terracotta.png"},
        {fr: "Terre cuite violette", buyPrice: 50, img: "../images/blocks/purple_terracotta.png"},
        {fr: "Terre cuite bleue", buyPrice: 50, img: "../images/blocks/blue_terracotta.png"},
        {fr: "Terre cuite marron", buyPrice: 50, img: "../images/blocks/brown_terracotta.png"},
        {fr: "Terre cuite verte", buyPrice: 50, img: "../images/blocks/green_terracotta.png"},
        {fr: "Terre cuite rouge", buyPrice: 50, img: "../images/blocks/red_terracotta.png"},
        {fr: "Terre cuite noire", buyPrice: 50, img: "../images/blocks/black_terracotta.png"},
        {fr: "Terre cuite émaillée blanche", buyPrice: 50, img: "../images/blocks/white_glazed_terracotta.png"},
        {fr: "Terre cuite émaillée orange", buyPrice: 50, img: "../images/blocks/orange_glazed_terracotta.png"},
        {fr: "Terre cuite émaillée magenta", buyPrice: 50, img: "../images/blocks/magenta_glazed_terracotta.png"},
        {fr: "Terre cuite émaillée bleu clair", buyPrice: 50, img: "../images/blocks/light_blue_glazed_terracotta.png"},
        {fr: "Terre cuite émaillée jaune", buyPrice: 50, img: "../images/blocks/yellow_glazed_terracotta.png"},
        {fr: "Terre cuite émaillée citron vert", buyPrice: 50, img: "../images/blocks/lime_glazed_terracotta.png"},
        {fr: "Terre cuite émaillée rose", buyPrice: 50, img: "../images/blocks/pink_glazed_terracotta.png"},
        {fr: "Terre cuite émaillée grise", buyPrice: 50, img: "../images/blocks/gray_glazed_terracotta.png"},
        {fr: "Terre cuite émaillée gris clair", buyPrice: 50, img: "../images/blocks/light_gray_glazed_terracotta.png"},
        {fr: "Terre cuite émaillée violette", buyPrice: 50, img: "../images/blocks/purple_glazed_terracotta.png"},
        {fr: "Terre cuite émaillée bleue", buyPrice: 50, img: "../images/blocks/blue_glazed_terracotta.png"},
        {fr: "Terre cuite émaillée marron", buyPrice: 50, img: "../images/blocks/brown_glazed_terracotta.png"},
        {fr: "Terre cuite émaillée verte", buyPrice: 50, img: "../images/blocks/green_glazed_terracotta.png"},
        {fr: "Terre cuite émaillée rouge", buyPrice: 50, img: "../images/blocks/red_glazed_terracotta.png"},
        {fr: "Terre cuite émaillée noire", buyPrice: 50, img: "../images/blocks/black_glazed_terracotta.png"},
        {fr: "Béton blanc", buyPrice: 50, img: "../images/blocks/white_concrete.png"},
        {fr: "Béton orange", buyPrice: 50, img: "../images/blocks/orange_concrete.png"},
        {fr: "Béton magenta", buyPrice: 50, img: "../images/blocks/magenta_concrete.png"},
        {fr: "Béton bleu clair", buyPrice: 50, img: "../images/blocks/light_blue_concrete.png"},
        {fr: "Béton jaune", buyPrice: 50, img: "../images/blocks/yellow_concrete.png"},
        {fr: "Béton citron vert", buyPrice: 50, img: "../images/blocks/lime_concrete.png"},
        {fr: "Béton rose", buyPrice: 50, img: "../images/blocks/pink_concrete.png"},
        {fr: "Béton gris", buyPrice: 50, img: "../images/blocks/gray_concrete.png"},
        {fr: "Béton gris clair", buyPrice: 50, img: "../images/blocks/light_gray_concrete.png"},
        {fr: "Béton cyan", buyPrice: 50, img: "../images/blocks/cyan_concrete.png"},
        {fr: "Béton violet", buyPrice: 50, img: "../images/blocks/purple_concrete.png"},
        {fr: "Béton bleu", buyPrice: 50, img: "../images/blocks/blue_concrete.png"},
        {fr: "Béton marron", buyPrice: 50, img: "../images/blocks/brown_concrete.png"},
        {fr: "Béton vert", buyPrice: 50, img: "../images/blocks/green_concrete.png"},
        {fr: "Béton rouge", buyPrice: 50, img: "../images/blocks/red_concrete.png"},
        {fr: "Béton noir", buyPrice: 50, img: "../images/blocks/black_concrete.png"},
        {fr: "Poudre de béton blanche", buyPrice: 50, img: "../images/blocks/white_concrete_powder.png"},
        {fr: "Poudre de béton orange", buyPrice: 50, img: "../images/blocks/orange_concrete_powder.png"},
        {fr: "Poudre de béton magenta", buyPrice: 50, img: "../images/blocks/magenta_concrete_powder.png"},
        {fr: "Poudre de béton bleu clair", buyPrice: 50, img: "../images/blocks/light_blue_concrete_powder.png"},
        {fr: "Poudre de béton jaune", buyPrice: 50, img: "../images/blocks/yellow_concrete_powder.png"},
        {fr: "Poudre de béton citron vert", buyPrice: 50, img: "../images/blocks/lime_concrete_powder.png"},
        {fr: "Poudre de béton rose", buyPrice: 50, img: "../images/blocks/pink_concrete_powder.png"},
        {fr: "Poudre de béton grise", buyPrice: 50, img: "../images/blocks/gray_concrete_powder.png"},
        {fr: "Poudre de béton gris clair", buyPrice: 50, img: "../images/blocks/light_gray_concrete_powder.png"},
        {fr: "Poudre de béton cyan", buyPrice: 50, img: "../images/blocks/cyan_concrete_powder.png"},
        {fr: "Poudre de béton violette", buyPrice: 50, img: "../images/blocks/purple_concrete_powder.png"},
        {fr: "Poudre de béton bleue", buyPrice: 50, img: "../images/blocks/blue_concrete_powder.png"},
        {fr: "Poudre de béton marron", buyPrice: 50, img: "../images/blocks/brown_concrete_powder.png"},
        {fr: "Poudre de béton verte", buyPrice: 50, img: "../images/blocks/green_concrete_powder.png"},
        {fr: "Poudre de béton rouge", buyPrice: 50, img: "../images/blocks/red_concrete_powder.png"},
        {fr: "Poudre de béton noire", buyPrice: 50, img: "../images/blocks/black_concrete_powder.png"},
        {fr: "Laine blanche", buyPrice: 50, img: "../images/blocks/white_wool.png"},
        {fr: "Laine orange", buyPrice: 50, img: "../images/blocks/orange_wool.png"},
        {fr: "Laine magenta", buyPrice: 50, img: "../images/blocks/magenta_wool.png"},
        {fr: "Laine bleu clair", buyPrice: 50, img: "../images/blocks/light_blue_wool.png"},
        {fr: "Laine jaune", buyPrice: 50, img: "../images/blocks/yellow_wool.png"},
        {fr: "Laine citron vert", buyPrice: 50, img: "../images/blocks/lime_wool.png"},
        {fr: "Laine rose", buyPrice: 50, img: "../images/blocks/pink_wool.png"},
        {fr: "Laine grise", buyPrice: 50, img: "../images/blocks/gray_wool.png"},
        {fr: "Laine gris clair", buyPrice: 50, img: "../images/blocks/light_gray_wool.png"},
        {fr: "Laine violette", buyPrice: 50, img: "../images/blocks/purple_wool.png"},
        {fr: "Laine bleue", buyPrice: 50, img: "../images/blocks/blue_wool.png"},
        {fr: "Laine marron", buyPrice: 50, img: "../images/blocks/brown_wool.png"},
        {fr: "Laine verte", buyPrice: 50, img: "../images/blocks/green_wool.png"},
        {fr: "Laine rouge", buyPrice: 50, img: "../images/blocks/red_wool.png"},
        {fr: "Laine noire", buyPrice: 50, img: "../images/blocks/black_wool.png"},
        {fr: "Lanterne aquatique", buyPrice: 50, img: "../images/blocks/sea_lantern.png"},
        {fr: "Pierre de l'End", buyPrice: 50, img: "../images/blocks/end_stone.png"},
        {fr: "Pierre lumineuse", buyPrice: 50, img: "../images/blocks/glowstone.png"},
        {fr: "Bloc de quartz", buyPrice: 50, img: "../images/blocks/quartz_block.png"},
        {fr: "Prismarine", buyPrice: 50, img: "../images/blocks/prismarine.png"},
        {fr: "Briques de prismarine", buyPrice: 50, img: "../images/blocks/prismarine_bricks.png"},
        {fr: "Prismarine sombre", buyPrice: 50, img: "../images/blocks/dark_prismarine.png"},
        {fr: "Terre cuite", buyPrice: 50, img: "../images/blocks/terracotta.png"},
        {fr: "Bloc de neige", buyPrice: 20, img: "../images/blocks/snow_block.png"},
        {fr: "Glace compactée", buyPrice: 100, img: "../images/blocks/packed_ice.png"},
        {fr: "Glace bleue", buyPrice: 100, img: "../images/blocks/blue_ice.png"},
        {fr: "Verre", buyPrice: 100, img: "../images/blocks/glass.png"},
        {fr: "Briques", buyPrice: 100, img: "../images/blocks/bricks.png"},
        {fr: "Barreaux de fer", buyPrice: 100, img: "../images/blocks/iron_bars.png"},
        {fr: "Pot de fleurs", buyPrice: 100, img: "../images/items/flower_pot.png"},
        {fr: "Dalle en chêne", buyPrice: 100, img: "../images/blocks/oak_slab.png"},
        {fr: "Dalle en sapin", buyPrice: 100, img: "../images/blocks/spruce_slab.png"},
        {fr: "Dalle en bouleau", buyPrice: 100, img: "../images/blocks/birch_slab.png"},
        {fr: "Dalle en acacia", buyPrice: 100, img: "../images/blocks/acacia_slab.png"},
        {fr: "Dalle en acajou", buyPrice: 100, img: "../images/blocks/jungle_slab.png"},
        {fr: "Dalle en chêne noir", buyPrice: 100, img: "../images/blocks/dark_oak_slab.png"},
        {fr: "Dalle en brique", buyPrice: 100, img: "../images/blocks/brick_slab.png"},
        {fr: "Dalle en pierre lisse", buyPrice: 100, img: "../images/blocks/smooth_stone_slab.png"},
        {fr: "Dalle en prismarine", buyPrice: 100, img: "../images/blocks/prismarine_slab.png"},
        {fr: "Dalle en prismarine sombre", buyPrice: 100, img: "../images/blocks/dark_prismarine_slab.png"},
        {fr: "Dalle en grès", buyPrice: 100, img: "../images/blocks/sandstone_slab.png"},
        {fr: "Dalle en grès rouge", buyPrice: 100, img: "../images/blocks/red_sandstone_slab.png"},
        {fr: "Escalier en chêne", buyPrice: 100, img: "../images/blocks/oak_stairs.png"},
        {fr: "Escalier en sapin", buyPrice: 100, img: "../images/blocks/spruce_stairs.png"},
        {fr: "Escalier en bouleau", buyPrice: 100, img: "../images/blocks/birch_stairs.png"},
        {fr: "Escalier en acacia", buyPrice: 100, img: "../images/blocks/acacia_stairs.png"},
        {fr: "Escalier en acajou", buyPrice: 100, img: "../images/blocks/jungle_stairs.png"},
        {fr: "Escalier en chêne noir", buyPrice: 100, img: "../images/blocks/dark_oak_stairs.png"},
        {fr: "Escalier en brique", buyPrice: 100, img: "../images/blocks/brick_stairs.png"},
        {fr: "Escalier en prismarine", buyPrice: 100, img: "../images/blocks/prismarine_stairs.png"},
        {fr: "Escalier en prismarine sombre", buyPrice: 100, img: "../images/blocks/dark_prismarine_stairs.png"},
        {fr: "Escalier en grès", buyPrice: 100, img: "../images/blocks/sandstone_stairs.png"},
        {fr: "Escalier en grès rouge", buyPrice: 100, img: "../images/blocks/red_sandstone_stairs.png"},
        {fr: "Porte en chêne", buyPrice: 100, img: "../images/items/oak_door.png"},
        {fr: "Porte en sapin", buyPrice: 100, img: "../images/items/spruce_door.png"},
        {fr: "Porte en bouleau", buyPrice: 100, img: "../images/items/birch_door.png"},
        {fr: "Porte en acacia", buyPrice: 100, img: "../images/items/acacia_door.png"},
        {fr: "Porte en acajou", buyPrice: 100, img: "../images/items/jungle_door.png"},
        {fr: "Porte en chêne noir", buyPrice: 100, img: "../images/items/dark_oak_door.png"},
        {fr: "Barrière en chêne", buyPrice: 100, img: "../images/blocks/oak_fence.png"},
        {fr: "Barrière en sapin", buyPrice: 100, img: "../images/blocks/spruce_fence.png"},
        {fr: "Barrière en bouleau", buyPrice: 100, img: "../images/blocks/birch_fence.png"},
        {fr: "Barrière en acacia", buyPrice: 100, img: "../images/blocks/acacia_fence.png"},
        {fr: "Barrière en acajou", buyPrice: 100, img: "../images/blocks/jungle_fence.png"},
        {fr: "Barrière en chêne noir", buyPrice: 100, img: "../images/blocks/dark_oak_fence.png"},
        {fr: "Portillon en chêne", buyPrice: 100, img: "../images/blocks/oak_fence_gate.png"},
        {fr: "Portillon en sapin", buyPrice: 100, img: "../images/blocks/spruce_fence_gate.png"},
        {fr: "Portillon en bouleau", buyPrice: 100, img: "../images/blocks/birch_fence_gate.png"},
        {fr: "Portillon en acacia", buyPrice: 100, img: "../images/blocks/acacia_fence_gate.png"},
        {fr: "Portillon en acajou", buyPrice: 100, img: "../images/blocks/jungle_fence_gate.png"},
        {fr: "Portillon en chêne noir", buyPrice: 100, img: "../images/blocks/dark_oak_fence_gate.png"},
        {fr: "Trappe en chêne", buyPrice: 100, img: "../images/blocks/oak_trapdoor.png"},
        {fr: "Trappe en sapin", buyPrice: 100, img: "../images/blocks/spruce_trapdoor.png"},
        {fr: "Trappe en bouleau", buyPrice: 100, img: "../images/blocks/birch_trapdoor.png"},
        {fr: "Trappe en acacia", buyPrice: 100, img: "../images/blocks/acacia_trapdoor.png"},
        {fr: "Trappe en acajou", buyPrice: 100, img: "../images/blocks/jungle_trapdoor.png"},
        {fr: "Trappe en chêne noir", buyPrice: 100, img: "../images/blocks/dark_oak_trapdoor.png"},
        {fr: "Pancarte en chêne", buyPrice: 100, img: "../images/items/oak_sign.png"},
        {fr: "Pancarte en sapin", buyPrice: 100, img: "../images/items/spruce_sign.png"},
        {fr: "Pancarte en bouleau", buyPrice: 100, img: "../images/items/birch_sign.png"},
        {fr: "Pancarte en acacia", buyPrice: 100, img: "../images/items/acacia_sign.png"},
        {fr: "Pancarte en acajou", buyPrice: 100, img: "../images/items/jungle_sign.png"},
        {fr: "Pancarte en chêne noir", buyPrice: 100, img: "../images/items/dark_oak_sign.png"},
        {fr: "Verre teinté blanc", buyPrice: 50, img: "../images/blocks/white_stained_glass.png"},
        {fr: "Verre teinté orange", buyPrice: 50, img: "../images/blocks/orange_stained_glass.png"},
        {fr: "Verre teinté magenta", buyPrice: 50, img: "../images/blocks/magenta_stained_glass.png"},
        {fr: "Verre teinté bleu clair", buyPrice: 50, img: "../images/blocks/light_blue_stained_glass.png"},
        {fr: "Verre teinté jaune", buyPrice: 50, img: "../images/blocks/yellow_stained_glass.png"},
        {fr: "Verre teinté citron vert", buyPrice: 50, img: "../images/blocks/lime_stained_glass.png"},
        {fr: "Verre teinté rose", buyPrice: 50, img: "../images/blocks/pink_stained_glass.png"},
        {fr: "Verre teinté gris", buyPrice: 50, img: "../images/blocks/gray_stained_glass.png"},
        {fr: "Verre teinté gris clair", buyPrice: 50, img: "../images/blocks/light_gray_stained_glass.png"},
        {fr: "Verre teinté violet", buyPrice: 50, img: "../images/blocks/purple_stained_glass.png"},
        {fr: "Verre teinté bleu", buyPrice: 50, img: "../images/blocks/blue_stained_glass.png"},
        {fr: "Verre teinté marron", buyPrice: 50, img: "../images/blocks/brown_stained_glass.png"},
        {fr: "Verre teinté vert", buyPrice: 50, img: "../images/blocks/green_stained_glass.png"},
        {fr: "Verre teinté rouge", buyPrice: 50, img: "../images/blocks/red_stained_glass.png"},
        {fr: "Verre teinté noir", buyPrice: 50, img: "../images/blocks/black_stained_glass.png"},
        {fr: "Tapis blanc", buyPrice: 50, img: "../images/blocks/white_carpet.png"},
        {fr: "Tapis orange", buyPrice: 50, img: "../images/blocks/orange_carpet.png"},
        {fr: "Tapis magenta", buyPrice: 50, img: "../images/blocks/magenta_carpet.png"},
        {fr: "Tapis bleu clair", buyPrice: 50, img: "../images/blocks/light_blue_carpet.png"},
        {fr: "Tapis jaune", buyPrice: 50, img: "../images/blocks/yellow_carpet.png"},
        {fr: "Tapis citron vert", buyPrice: 50, img: "../images/blocks/lime_carpet.png"},
        {fr: "Tapis rose", buyPrice: 50, img: "../images/blocks/pink_carpet.png"},
        {fr: "Tapis gris", buyPrice: 50, img: "../images/blocks/gray_carpet.png"},
        {fr: "Tapis gris clair", buyPrice: 50, img: "../images/blocks/light_gray_carpet.png"},
        {fr: "Tapis violet", buyPrice: 50, img: "../images/blocks/purple_carpet.png"},
        {fr: "Tapis bleu", buyPrice: 50, img: "../images/blocks/blue_carpet.png"},
        {fr: "Tapis marron", buyPrice: 50, img: "../images/blocks/brown_carpet.png"},
        {fr: "Tapis vert", buyPrice: 50, img: "../images/blocks/green_carpet.png"},
        {fr: "Tapis rouge", buyPrice: 50, img: "../images/blocks/red_carpet.png"},
        {fr: "Tapis noir", buyPrice: 50, img: "../images/blocks/black_carpet.png"},
        {fr: "Toile d'araignée", buyPrice: 50, img: "../images/blocks/cobweb.png"},
        {fr: "Échelle", buyPrice: 50, img: "../images/items/ladder.png"},
        {fr: "Lanterne", buyPrice: 50, img: "../images/items/lantern.png"},
        {fr: "Lampe de Redstone", buyPrice: 50, img: "../images/blocks/redstone_lamp.png"}
    ]
};