// Ce fichier contient les patrons de fabrication pour le générateur de recettes.
// Il est conçu pour être facilement lu et utilisé par le script principal.

// Définitions des groupes d'items pour simplifier les recettes
const RECIPE_VARIANTS = {
    "planks": [
        "minecraft:oak_planks",
        "minecraft:spruce_planks",
        "minecraft:birch_planks",
        "minecraft:jungle_planks",
        "minecraft:acacia_planks",
        "minecraft:dark_oak_planks",
        "minecraft:mangrove_planks",
        "minecraft:cherry_planks"
    ],
    "logs": [
        "minecraft:oak_log",
        "minecraft:spruce_log",
        "minecraft:birch_log",
        "minecraft:jungle_log",
        "minecraft:acacia_log",
        "minecraft:dark_oak_log",
        "minecraft:mangrove_log",
        "minecraft:cherry_log"
    ],
    "stripped_logs": [
        "minecraft:stripped_oak_log",
        "minecraft:stripped_spruce_log",
        "minecraft:stripped_birch_log",
        "minecraft:stripped_jungle_log",
        "minecraft:stripped_acacia_log",
        "minecraft:stripped_dark_oak_log",
        "minecraft:stripped_mangrove_log",
        "minecraft:stripped_cherry_log"
    ],
    "wood": [
         "minecraft:oak_wood",
        "minecraft:spruce_wood",
        "minecraft:birch_wood",
        "minecraft:jungle_wood",
        "minecraft:acacia_wood",
        "minecraft:dark_oak_wood",
        "minecraft:mangrove_wood",
        "minecraft:cherry_wood"
    ],
    "stripped_wood": [
        "minecraft:stripped_oak_wood",
        "minecraft:stripped_spruce_wood",
        "minecraft:stripped_birch_wood",
        "minecraft:stripped_jungle_wood",
        "minecraft:stripped_acacia_wood",
        "minecraft:stripped_dark_oak_wood",
        "minecraft:stripped_mangrove_wood",
        "minecraft:stripped_cherry_wood"
    ],
    "stone_crafting_materials": [
        "minecraft:cobblestone",
        "minecraft:blackstone"
    ],
    "stone_bricks": [
        "minecraft:stone_bricks",
        "minecraft:polished_blackstone_bricks",
        "minecraft:deepslate_bricks",
        "minecraft:mud_bricks"
    ],
    "wool": [
        "minecraft:white_wool", "minecraft:orange_wool", "minecraft:magenta_wool", "minecraft:light_blue_wool",
        "minecraft:yellow_wool", "minecraft:lime_wool", "minecraft:pink_wool", "minecraft:gray_wool",
        "minecraft:light_gray_wool", "minecraft:cyan_wool", "minecraft:purple_wool", "minecraft:blue_wool",
        "minecraft:brown_wool", "minecraft:green_wool", "minecraft:red_wool", "minecraft:black_wool"
    ],
    "dyes": [
        "minecraft:white_dye", "minecraft:orange_dye", "minecraft:magenta_dye", "minecraft:light_blue_dye",
        "minecraft:yellow_dye", "minecraft:lime_dye", "minecraft:pink_dye", "minecraft:gray_dye",
        "minecraft:light_gray_dye", "minecraft:cyan_dye", "minecraft:purple_dye", "minecraft:blue_dye",
        "minecraft:brown_dye", "minecraft:green_dye", "minecraft:red_dye", "minecraft:black_dye"
    ]
};


const CRAFTING_RECIPES = {
    // A
    "minecraft:acacia_boat": { "type": "shaped", "pattern": ["P P", "PPP"], "ingredients": { "P": ["minecraft:acacia_planks"] } },
    "minecraft:acacia_button": { "type": "shapeless", "ingredients": ["minecraft:acacia_planks"] },
    "minecraft:acacia_chest_boat": { "type": "shapeless", "ingredients": ["minecraft:chest", "minecraft:acacia_boat"] },
    "minecraft:acacia_door": { "type": "shaped", "pattern": ["PP", "PP", "PP"], "ingredients": { "P": ["minecraft:acacia_planks"] } },
    "minecraft:acacia_fence": { "type": "shaped", "pattern": ["PSP", "PSP"], "ingredients": { "P": ["minecraft:acacia_planks"], "S": ["minecraft:stick"] } },
    "minecraft:acacia_fence_gate": { "type": "shaped", "pattern": ["SPS", "SPS"], "ingredients": { "P": ["minecraft:acacia_planks"], "S": ["minecraft:stick"] } },
    "minecraft:acacia_hanging_sign": { "type": "shaped", "pattern": ["C C", "S S"], "ingredients": { "C": ["minecraft:chain"], "S": ["minecraft:stripped_acacia_log"] } },
    "minecraft:acacia_planks": { "type": "shapeless", "ingredients": ["minecraft:acacia_log"] },
    "minecraft:acacia_pressure_plate": { "type": "shaped", "pattern": ["PP"], "ingredients": { "P": ["minecraft:acacia_planks"] } },
    "minecraft:acacia_sign": { "type": "shaped", "pattern": ["PPP", "PPP", " S "], "ingredients": { "P": ["minecraft:acacia_planks"], "S": ["minecraft:stick"] } },
    "minecraft:acacia_slab": { "type": "shaped", "pattern": ["PPP"], "ingredients": { "P": ["minecraft:acacia_planks"] } },
    "minecraft:acacia_stairs": { "type": "shaped", "pattern": ["P  ", "PP ", "PPP"], "ingredients": { "P": ["minecraft:acacia_planks"] } },
    "minecraft:acacia_trapdoor": { "type": "shaped", "pattern": ["PPP", "PPP"], "ingredients": { "P": ["minecraft:acacia_planks"] } },
    "minecraft:acacia_wood": { "type": "shaped", "pattern": ["LL", "LL"], "ingredients": { "L": ["minecraft:acacia_log"] } },
    "minecraft:activator_rail": { "type": "shaped", "pattern": ["ISI", "SRS", "ISI"], "ingredients": { "I": ["minecraft:iron_ingot"], "S": ["minecraft:stick"], "R": ["minecraft:redstone_torch"] } },
    "minecraft:amethyst_block": { "type": "shaped", "pattern": ["SS", "SS"], "ingredients": { "S": ["minecraft:amethyst_shard"] } },
    "minecraft:andesite_slab": { "type": "shaped", "pattern": ["AAA"], "ingredients": { "A": ["minecraft:andesite"] } },
    "minecraft:andesite_stairs": { "type": "shaped", "pattern": ["A  ", "AA ", "AAA"], "ingredients": { "A": ["minecraft:andesite"] } },
    "minecraft:andesite_wall": { "type": "shaped", "pattern": ["AAA", "AAA"], "ingredients": { "A": ["minecraft:andesite"] } },
    "minecraft:anvil": { "type": "shaped", "pattern": ["BBB", " I ", "III"], "ingredients": { "B": ["minecraft:iron_block"], "I": ["minecraft:iron_ingot"] } },
    "minecraft:armor_stand": { "type": "shaped", "pattern": [" S ", "SSS", "SPS"], "ingredients": { "S": ["minecraft:stick"], "P": ["minecraft:smooth_stone_slab"] } },
    "minecraft:arrow": { "type": "shaped", "pattern": ["F", "S", "E"], "ingredients": { "F": ["minecraft:flint"], "S": ["minecraft:stick"], "E": ["minecraft:feather"] } },

    // B
    "minecraft:bamboo_block": { "type": "shaped", "pattern": ["BBB", "BBB", "BBB"], "ingredients": { "B": ["minecraft:bamboo"] } },
    "minecraft:bamboo_button": { "type": "shapeless", "ingredients": ["minecraft:bamboo_planks"] },
    "minecraft:bamboo_chest_raft": { "type": "shapeless", "ingredients": ["minecraft:chest", "minecraft:bamboo_raft"] },
    "minecraft:bamboo_door": { "type": "shaped", "pattern": ["PP", "PP", "PP"], "ingredients": { "P": ["minecraft:bamboo_planks"] } },
    "minecraft:bamboo_fence": { "type": "shaped", "pattern": ["PSP", "PSP"], "ingredients": { "P": ["minecraft:bamboo_planks"], "S": ["minecraft:stick"] } },
    "minecraft:bamboo_fence_gate": { "type": "shaped", "pattern": ["SPS", "SPS"], "ingredients": { "P": ["minecraft:bamboo_planks"], "S": ["minecraft:stick"] } },
    "minecraft:bamboo_hanging_sign": { "type": "shaped", "pattern": ["C C", "S S"], "ingredients": { "C": ["minecraft:chain"], "S": ["minecraft:stripped_bamboo_block"] } },
    "minecraft:bamboo_mosaic": { "type": "shaped", "pattern": ["S", "S"], "ingredients": { "S": ["minecraft:bamboo_slab"] } },
    "minecraft:bamboo_mosaic_slab": { "type": "shaped", "pattern": ["MMM"], "ingredients": { "M": ["minecraft:bamboo_mosaic"] } },
    "minecraft:bamboo_mosaic_stairs": { "type": "shaped", "pattern": ["M  ", "MM ", "MMM"], "ingredients": { "M": ["minecraft:bamboo_mosaic"] } },
    "minecraft:bamboo_planks": { "type": "shapeless", "ingredients": ["minecraft:bamboo_block"] },
    "minecraft:bamboo_pressure_plate": { "type": "shaped", "pattern": ["PP"], "ingredients": { "P": ["minecraft:bamboo_planks"] } },
    "minecraft:bamboo_raft": { "type": "shaped", "pattern": ["P P", "PPP"], "ingredients": { "P": ["minecraft:bamboo_planks"] } },
    "minecraft:bamboo_sign": { "type": "shaped", "pattern": ["PPP", "PPP", " S "], "ingredients": { "P": ["minecraft:bamboo_planks"], "S": ["minecraft:stick"] } },
    "minecraft:bamboo_slab": { "type": "shaped", "pattern": ["PPP"], "ingredients": { "P": ["minecraft:bamboo_planks"] } },
    "minecraft:bamboo_stairs": { "type": "shaped", "pattern": ["P  ", "PP ", "PPP"], "ingredients": { "P": ["minecraft:bamboo_planks"] } },
    "minecraft:bamboo_trapdoor": { "type": "shaped", "pattern": ["PPP", "PPP"], "ingredients": { "P": ["minecraft:bamboo_planks"] } },
    "minecraft:barrel": { "type": "shaped", "pattern": ["PSP", "P P", "PSP"], "ingredients": { "P": RECIPE_VARIANTS.planks, "S": ["minecraft:oak_slab", "minecraft:spruce_slab", "minecraft:birch_slab", "minecraft:jungle_slab", "minecraft:acacia_slab", "minecraft:dark_oak_slab", "minecraft:mangrove_slab", "minecraft:cherry_slab", "minecraft:bamboo_slab", "minecraft:crimson_slab", "minecraft:warped_slab"] } },
    "minecraft:beacon": { "type": "shaped", "pattern": ["GGG", "GSG", "OOO"], "ingredients": { "G": ["minecraft:glass"], "S": ["minecraft:nether_star"], "O": ["minecraft:obsidian"] } },
    "minecraft:beehive": { "type": "shaped", "pattern": ["PPP", "HHH", "PPP"], "ingredients": { "P": RECIPE_VARIANTS.planks, "H": ["minecraft:honeycomb"] } },
    "minecraft:beetroot_soup": { "type": "shaped", "pattern": ["BBB", "BBB", " V "], "ingredients": { "B": ["minecraft:beetroot"], "V": ["minecraft:bowl"] } },
    "minecraft:birch_boat": { "type": "shaped", "pattern": ["P P", "PPP"], "ingredients": { "P": ["minecraft:birch_planks"] } },
    "minecraft:birch_button": { "type": "shapeless", "ingredients": ["minecraft:birch_planks"] },
    "minecraft:birch_chest_boat": { "type": "shapeless", "ingredients": ["minecraft:chest", "minecraft:birch_boat"] },
    "minecraft:birch_door": { "type": "shaped", "pattern": ["PP", "PP", "PP"], "ingredients": { "P": ["minecraft:birch_planks"] } },
    "minecraft:birch_fence": { "type": "shaped", "pattern": ["PSP", "PSP"], "ingredients": { "P": ["minecraft:birch_planks"], "S": ["minecraft:stick"] } },
    "minecraft:birch_fence_gate": { "type": "shaped", "pattern": ["SPS", "SPS"], "ingredients": { "P": ["minecraft:birch_planks"], "S": ["minecraft:stick"] } },
    "minecraft:birch_hanging_sign": { "type": "shaped", "pattern": ["C C", "S S"], "ingredients": { "C": ["minecraft:chain"], "S": ["minecraft:stripped_birch_log"] } },
    "minecraft:birch_planks": { "type": "shapeless", "ingredients": ["minecraft:birch_log"] },
    "minecraft:birch_pressure_plate": { "type": "shaped", "pattern": ["PP"], "ingredients": { "P": ["minecraft:birch_planks"] } },
    "minecraft:birch_sign": { "type": "shaped", "pattern": ["PPP", "PPP", " S "], "ingredients": { "P": ["minecraft:birch_planks"], "S": ["minecraft:stick"] } },
    "minecraft:birch_slab": { "type": "shaped", "pattern": ["PPP"], "ingredients": { "P": ["minecraft:birch_planks"] } },
    "minecraft:birch_stairs": { "type": "shaped", "pattern": ["P  ", "PP ", "PPP"], "ingredients": { "P": ["minecraft:birch_planks"] } },
    "minecraft:birch_trapdoor": { "type": "shaped", "pattern": ["PPP", "PPP"], "ingredients": { "P": ["minecraft:birch_planks"] } },
    "minecraft:birch_wood": { "type": "shaped", "pattern": ["LL", "LL"], "ingredients": { "L": ["minecraft:birch_log"] } },
    "minecraft:black_banner": { "type": "shaped", "pattern": ["WWW", "WWW", " S "], "ingredients": { "W": ["minecraft:black_wool"], "S": ["minecraft:stick"] } },
    "minecraft:black_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:black_wool"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:black_candle": { "type": "shapeless", "ingredients": ["minecraft:candle", "minecraft:black_dye"] },
    "minecraft:black_carpet": { "type": "shaped", "pattern": ["WW"], "ingredients": { "W": ["minecraft:black_wool"] } },
    "minecraft:black_dye": { "type": "shapeless", "ingredients": ["minecraft:ink_sac", "minecraft:wither_rose"] },
    "minecraft:black_stained_glass": { "type": "shaped", "pattern": ["GGG", "GDG", "GGG"], "ingredients": { "G": ["minecraft:glass"], "D": ["minecraft:black_dye"] } },
    "minecraft:black_stained_glass_pane": { "type": "shaped", "pattern": ["GGG", "GGG"], "ingredients": { "G": ["minecraft:black_stained_glass"] } },
    "minecraft:black_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:black_dye"] },
    "minecraft:blast_furnace": { "type": "shaped", "pattern": ["III", "IFI", "SSS"], "ingredients": { "I": ["minecraft:iron_ingot"], "F": ["minecraft:furnace"], "S": ["minecraft:smooth_stone"] } },
    "minecraft:blaze_powder": { "type": "shapeless", "ingredients": ["minecraft:blaze_rod"] },
    "minecraft:blue_dye": { "type": "shapeless", "ingredients": ["minecraft:lapis_lazuli", "minecraft:cornflower"] },
    "minecraft:bone_block": { "type": "shaped", "pattern": ["MMM", "MMM", "MMM"], "ingredients": { "M": ["minecraft:bone_meal"] } },
    "minecraft:bone_meal": { "type": "shapeless", "ingredients": ["minecraft:bone"] },
    "minecraft:book": { "type": "shapeless", "ingredients": ["minecraft:paper", "minecraft:paper", "minecraft:paper", "minecraft:leather"] },
    "minecraft:bookshelf": { "type": "shaped", "pattern": ["PPP", "BBB", "PPP"], "ingredients": { "P": RECIPE_VARIANTS.planks, "B": ["minecraft:book"] } },
    "minecraft:bow": { "type": "shaped", "pattern": [" ST", "S T", " ST"], "ingredients": { "S": ["minecraft:stick"], "T": ["minecraft:string"] } },
    "minecraft:bowl": { "type": "shaped", "pattern": ["P P", " P "], "ingredients": { "P": RECIPE_VARIANTS.planks } },
    "minecraft:bread": { "type": "shaped", "pattern": ["WWW"], "ingredients": { "W": ["minecraft:wheat"] } },
    "minecraft:brewing_stand": { "type": "shaped", "pattern": [" R ", "CCC"], "ingredients": { "R": ["minecraft:blaze_rod"], "C": RECIPE_VARIANTS.stone_crafting_materials } },
    "minecraft:brick_slab": { "type": "shaped", "pattern": ["BBB"], "ingredients": { "B": ["minecraft:bricks"] } },
    "minecraft:brick_stairs": { "type": "shaped", "pattern": ["B  ", "BB ", "BBB"], "ingredients": { "B": ["minecraft:bricks"] } },
    "minecraft:brick_wall": { "type": "shaped", "pattern": ["BBB", "BBB"], "ingredients": { "B": ["minecraft:bricks"] } },
    "minecraft:bricks": { "type": "shaped", "pattern": ["BB", "BB"], "ingredients": { "B": ["minecraft:brick"] } },
    "minecraft:brown_dye": { "type": "shapeless", "ingredients": ["minecraft:cocoa_beans"] },
    "minecraft:brush": { "type": "shaped", "pattern": ["F", "I", "S"], "ingredients": { "F": ["minecraft:feather"], "I": ["minecraft:copper_ingot"], "S": ["minecraft:stick"] } },
    "minecraft:bucket": { "type": "shaped", "pattern": ["I I", " I "], "ingredients": { "I": ["minecraft:iron_ingot"] } },
    "minecraft:bundle": { "type": "shaped", "pattern": ["SHS", "H H", "HHH"], "ingredients": { "S": ["minecraft:string"], "H": ["minecraft:rabbit_hide"] } },

    // C
    "minecraft:cake": { "type": "shaped", "pattern": ["MMM", "SES", "WWW"], "ingredients": { "M": ["minecraft:milk_bucket"], "S": ["minecraft:sugar"], "E": ["minecraft:egg"], "W": ["minecraft:wheat"] } },
    "minecraft:calibrated_sculk_sensor": { "type": "shaped", "pattern": [" A ", "SSS"], "ingredients": { "A": ["minecraft:amethyst_shard"], "S": ["minecraft:sculk_sensor"] } },
    "minecraft:campfire": { "type": "shaped", "pattern": [" S ", "SCS", "LLL"], "ingredients": { "S": ["minecraft:stick"], "C": ["minecraft:coal", "minecraft:charcoal"], "L": RECIPE_VARIANTS.logs } },
    "minecraft:candle": { "type": "shaped", "pattern": ["S", "H"], "ingredients": { "S": ["minecraft:string"], "H": ["minecraft:honeycomb"] } },
    "minecraft:carrot_on_a_stick": { "type": "shapeless", "ingredients": ["minecraft:fishing_rod", "minecraft:carrot"] },
    "minecraft:cartography_table": { "type": "shaped", "pattern": ["PP", "BB", "BB"], "ingredients": { "P": ["minecraft:paper"], "B": RECIPE_VARIANTS.planks } },
    "minecraft:cauldron": { "type": "shaped", "pattern": ["I I", "I I", "III"], "ingredients": { "I": ["minecraft:iron_ingot"] } },
    "minecraft:chain": { "type": "shaped", "pattern": ["N", "I", "N"], "ingredients": { "I": ["minecraft:iron_ingot"], "N": ["minecraft:iron_nugget"] } },
    "minecraft:charcoal": { "type": "furnace", "input": RECIPE_VARIANTS.logs },
    "minecraft:chest": { "type": "shaped", "pattern": ["PPP", "P P", "PPP"], "ingredients": { "P": RECIPE_VARIANTS.planks } },
    "minecraft:chest_minecart": { "type": "shapeless", "ingredients": ["minecraft:chest", "minecraft:minecart"] },
    "minecraft:chiseled_bookshelf": { "type": "shaped", "pattern": ["PPP", "SSS", "PPP"], "ingredients": { "P": RECIPE_VARIANTS.planks, "S": ["minecraft:oak_slab", "minecraft:spruce_slab", "minecraft:birch_slab", "minecraft:jungle_slab", "minecraft:acacia_slab", "minecraft:dark_oak_slab", "minecraft:mangrove_slab", "minecraft:cherry_slab", "minecraft:bamboo_slab", "minecraft:crimson_slab", "minecraft:warped_slab"] } },
    "minecraft:chiseled_deepslate": { "type": "shaped", "pattern": ["S", "S"], "ingredients": { "S": ["minecraft:cobbled_deepslate_slab"] } },
    "minecraft:chiseled_nether_bricks": { "type": "shaped", "pattern": ["S", "S"], "ingredients": { "S": ["minecraft:nether_brick_slab"] } },
    "minecraft:chiseled_polished_blackstone": { "type": "shaped", "pattern": ["S", "S"], "ingredients": { "S": ["minecraft:polished_blackstone_slab"] } },
    "minecraft:chiseled_quartz_block": { "type": "shaped", "pattern": ["S", "S"], "ingredients": { "S": ["minecraft:quartz_slab"] } },
    "minecraft:chiseled_red_sandstone": { "type": "shaped", "pattern": ["S", "S"], "ingredients": { "S": ["minecraft:red_sandstone_slab"] } },
    "minecraft:chiseled_sandstone": { "type": "shaped", "pattern": ["S", "S"], "ingredients": { "S": ["minecraft:sandstone_slab"] } },
    "minecraft:chiseled_stone_bricks": { "type": "shaped", "pattern": ["S", "S"], "ingredients": { "S": ["minecraft:stone_brick_slab"] } },
    "minecraft:clay": { "type": "shaped", "pattern": ["BB", "BB"], "ingredients": { "B": ["minecraft:clay_ball"] } },
    "minecraft:clock": { "type": "shaped", "pattern": [" G ", "GRG", " G "], "ingredients": { "G": ["minecraft:gold_ingot"], "R": ["minecraft:redstone"] } },
    "minecraft:coal_block": { "type": "shaped", "pattern": ["CCC", "CCC", "CCC"], "ingredients": { "C": ["minecraft:coal"] } },
    "minecraft:coarse_dirt": { "type": "shaped", "pattern": ["DG", "GD"], "ingredients": { "D": ["minecraft:dirt"], "G": ["minecraft:gravel"] } },
    "minecraft:cobblestone_slab": { "type": "shaped", "pattern": ["CCC"], "ingredients": { "C": ["minecraft:cobblestone"] } },
    "minecraft:cobblestone_stairs": { "type": "shaped", "pattern": ["C  ", "CC ", "CCC"], "ingredients": { "C": ["minecraft:cobblestone"] } },
    "minecraft:cobblestone_wall": { "type": "shaped", "pattern": ["CCC", "CCC"], "ingredients": { "C": ["minecraft:cobblestone"] } },
    "minecraft:comparator": { "type": "shaped", "pattern": [" R ", "RQR", "SSS"], "ingredients": { "R": ["minecraft:redstone_torch"], "Q": ["minecraft:quartz"], "S": ["minecraft:stone"] } },
    "minecraft:compass": { "type": "shaped", "pattern": [" I ", "IRI", " I "], "ingredients": { "I": ["minecraft:iron_ingot"], "R": ["minecraft:redstone"] } },
    "minecraft:composter": { "type": "shaped", "pattern": ["S S", "S S", "SSS"], "ingredients": { "S": ["minecraft:oak_slab", "minecraft:spruce_slab", "minecraft:birch_slab", "minecraft:jungle_slab", "minecraft:acacia_slab", "minecraft:dark_oak_slab", "minecraft:mangrove_slab", "minecraft:cherry_slab", "minecraft:bamboo_slab", "minecraft:crimson_slab", "minecraft:warped_slab"] } },
    "minecraft:conduit": { "type": "shaped", "pattern": ["SSS", "SHS", "SSS"], "ingredients": { "S": ["minecraft:nautilus_shell"], "H": ["minecraft:heart_of_the_sea"] } },
    "minecraft:cookie": { "type": "shaped", "pattern": ["WCW"], "ingredients": { "W": ["minecraft:wheat"], "C": ["minecraft:cocoa_beans"] } },
    "minecraft:copper_block": { "type": "shaped", "pattern": ["III", "III", "III"], "ingredients": { "I": ["minecraft:copper_ingot"] } },
    "minecraft:crafter": { "type": "shaped", "pattern": ["III", "CDC", "R R"], "ingredients": { "I": ["minecraft:iron_ingot"], "C": ["minecraft:crafting_table"], "D": ["minecraft:dropper"], "R": ["minecraft:redstone"] } },
    "minecraft:creeper_banner_pattern": { "type": "shapeless", "ingredients": ["minecraft:paper", "minecraft:creeper_head"] },
    "minecraft:crossbow": { "type": "shaped", "pattern": ["SIS", "STS", " S "], "ingredients": { "S": ["minecraft:stick"], "I": ["minecraft:iron_ingot"], "T": ["minecraft:tripwire_hook"] } },
    "minecraft:cut_copper": { "type": "shaped", "pattern": ["CC", "CC"], "ingredients": { "C": ["minecraft:copper_block"] } },
    "minecraft:cut_copper_slab": { "type": "shaped", "pattern": ["CCC"], "ingredients": { "C": ["minecraft:cut_copper"] } },
    "minecraft:cut_copper_stairs": { "type": "shaped", "pattern": ["C  ", "CC ", "CCC"], "ingredients": { "C": ["minecraft:cut_copper"] } },
    "minecraft:cyan_dye": { "type": "shapeless", "ingredients": ["minecraft:blue_dye", "minecraft:green_dye"] },
    
    // D
    "minecraft:dark_oak_boat": { "type": "shaped", "pattern": ["P P", "PPP"], "ingredients": { "P": ["minecraft:dark_oak_planks"] } },
    "minecraft:dark_oak_button": { "type": "shapeless", "ingredients": ["minecraft:dark_oak_planks"] },
    "minecraft:dark_oak_chest_boat": { "type": "shapeless", "ingredients": ["minecraft:chest", "minecraft:dark_oak_boat"] },
    "minecraft:dark_oak_door": { "type": "shaped", "pattern": ["PP", "PP", "PP"], "ingredients": { "P": ["minecraft:dark_oak_planks"] } },
    "minecraft:dark_oak_fence": { "type": "shaped", "pattern": ["PSP", "PSP"], "ingredients": { "P": ["minecraft:dark_oak_planks"], "S": ["minecraft:stick"] } },
    "minecraft:dark_oak_fence_gate": { "type": "shaped", "pattern": ["SPS", "SPS"], "ingredients": { "P": ["minecraft:dark_oak_planks"], "S": ["minecraft:stick"] } },
    "minecraft:dark_oak_hanging_sign": { "type": "shaped", "pattern": ["C C", "S S"], "ingredients": { "C": ["minecraft:chain"], "S": ["minecraft:stripped_dark_oak_log"] } },
    "minecraft:dark_oak_planks": { "type": "shapeless", "ingredients": ["minecraft:dark_oak_log"] },
    "minecraft:dark_oak_pressure_plate": { "type": "shaped", "pattern": ["PP"], "ingredients": { "P": ["minecraft:dark_oak_planks"] } },
    "minecraft:dark_oak_sign": { "type": "shaped", "pattern": ["PPP", "PPP", " S "], "ingredients": { "P": ["minecraft:dark_oak_planks"], "S": ["minecraft:stick"] } },
    "minecraft:dark_oak_slab": { "type": "shaped", "pattern": ["PPP"], "ingredients": { "P": ["minecraft:dark_oak_planks"] } },
    "minecraft:dark_oak_stairs": { "type": "shaped", "pattern": ["P  ", "PP ", "PPP"], "ingredients": { "P": ["minecraft:dark_oak_planks"] } },
    "minecraft:dark_oak_trapdoor": { "type": "shaped", "pattern": ["PPP", "PPP"], "ingredients": { "P": ["minecraft:dark_oak_planks"] } },
    "minecraft:dark_oak_wood": { "type": "shaped", "pattern": ["LL", "LL"], "ingredients": { "L": ["minecraft:dark_oak_log"] } },
    "minecraft:dark_prismarine": { "type": "shaped", "pattern": ["PPP", "PIP", "PPP"], "ingredients": { "P": ["minecraft:prismarine_shard"], "I": ["minecraft:ink_sac"] } },
    "minecraft:daylight_detector": { "type": "shaped", "pattern": ["GGG", "QQQ", "SSS"], "ingredients": { "G": ["minecraft:glass"], "Q": ["minecraft:quartz"], "S": ["minecraft:oak_slab", "minecraft:spruce_slab", "minecraft:birch_slab", "minecraft:jungle_slab", "minecraft:acacia_slab", "minecraft:dark_oak_slab", "minecraft:mangrove_slab", "minecraft:cherry_slab", "minecraft:bamboo_slab", "minecraft:crimson_slab", "minecraft:warped_slab"] } },
    "minecraft:decorated_pot": { "type": "shaped", "pattern": ["S", "B", "S"], "ingredients": { "S": ["minecraft:brick", "minecraft:angler_pottery_sherd", "minecraft:archer_pottery_sherd", "minecraft:arms_up_pottery_sherd", "minecraft:blade_pottery_sherd", "minecraft:brewer_pottery_sherd", "minecraft:burn_pottery_sherd", "minecraft:danger_pottery_sherd", "minecraft:explorer_pottery_sherd", "minecraft:friend_pottery_sherd", "minecraft:guster_pottery_sherd", "minecraft:heart_pottery_sherd", "minecraft:heartbreak_pottery_sherd", "minecraft:howl_pottery_sherd", "minecraft:miner_pottery_sherd", "minecraft:mourner_pottery_sherd", "minecraft:plenty_pottery_sherd", "minecraft:prize_pottery_sherd", "minecraft:scrape_pottery_sherd", "minecraft:sheaf_pottery_sherd", "minecraft:shelter_pottery_sherd", "minecraft:skull_pottery_sherd", "minecraft:snort_pottery_sherd"], "B": ["minecraft:brick"] } },
    "minecraft:detector_rail": { "type": "shaped", "pattern": ["I I", "IPI", "I I"], "ingredients": { "I": ["minecraft:iron_ingot"], "P": ["minecraft:stone_pressure_plate"], "R": ["minecraft:redstone"] } },
    "minecraft:diamond_axe": { "type": "shaped", "pattern": ["DD ", "DS ", " S "], "ingredients": { "D": ["minecraft:diamond"], "S": ["minecraft:stick"] } },
    "minecraft:diamond_block": { "type": "shaped", "pattern": ["DDD", "DDD", "DDD"], "ingredients": { "D": ["minecraft:diamond"] } },
    "minecraft:diamond_boots": { "type": "shaped", "pattern": ["D D", "D D"], "ingredients": { "D": ["minecraft:diamond"] } },
    "minecraft:diamond_chestplate": { "type": "shaped", "pattern": ["D D", "DDD", "DDD"], "ingredients": { "D": ["minecraft:diamond"] } },
    "minecraft:diamond_helmet": { "type": "shaped", "pattern": ["DDD", "D D"], "ingredients": { "D": ["minecraft:diamond"] } },
    "minecraft:diamond_hoe": { "type": "shaped", "pattern": ["DD", " S", " S"], "ingredients": { "D": ["minecraft:diamond"], "S": ["minecraft:stick"] } },
    "minecraft:diamond_leggings": { "type": "shaped", "pattern": ["DDD", "D D", "D D"], "ingredients": { "D": ["minecraft:diamond"] } },
    "minecraft:diamond_pickaxe": { "type": "shaped", "pattern": ["DDD", " S ", " S "], "ingredients": { "D": ["minecraft:diamond"], "S": ["minecraft:stick"] } },
    "minecraft:diamond_shovel": { "type": "shaped", "pattern": ["D", "S", "S"], "ingredients": { "D": ["minecraft:diamond"], "S": ["minecraft:stick"] } },
    "minecraft:diamond_sword": { "type": "shaped", "pattern": ["D", "D", "S"], "ingredients": { "D": ["minecraft:diamond"], "S": ["minecraft:stick"] } },
    "minecraft:diorite": { "type": "shaped", "pattern": ["CQ", "QC"], "ingredients": { "C": ["minecraft:cobblestone"], "Q": ["minecraft:quartz"] } },
    "minecraft:dispenser": { "type": "shaped", "pattern": ["CCC", "CBC", "CRC"], "ingredients": { "C": ["minecraft:cobblestone"], "B": ["minecraft:bow"], "R": ["minecraft:redstone"] } },
    "minecraft:dropper": { "type": "shaped", "pattern": ["CCC", "C C", "CRC"], "ingredients": { "C": ["minecraft:cobblestone"], "R": ["minecraft:redstone"] } },
    
    // E
    "minecraft:enchanting_table": { "type": "shaped", "pattern": [" B ", "DOD", "OOO"], "ingredients": { "B": ["minecraft:book"], "D": ["minecraft:diamond"], "O": ["minecraft:obsidian"] } },
    "minecraft:end_crystal": { "type": "shaped", "pattern": ["GGG", "GEG", "GTG"], "ingredients": { "G": ["minecraft:glass"], "E": ["minecraft:ender_eye"], "T": ["minecraft:ghast_tear"] } },
    "minecraft:end_rod": { "type": "shaped", "pattern": ["B", "C"], "ingredients": { "B": ["minecraft:blaze_rod"], "C": ["minecraft:popped_chorus_fruit"] } },
    "minecraft:end_stone_bricks": { "type": "shaped", "pattern": ["EE", "EE"], "ingredients": { "E": ["minecraft:end_stone"] } },
    "minecraft:ender_chest": { "type": "shaped", "pattern": ["OOO", "OEO", "OOO"], "ingredients": { "O": ["minecraft:obsidian"], "E": ["minecraft:ender_eye"] } },
    "minecraft:ender_eye": { "type": "shapeless", "ingredients": ["minecraft:ender_pearl", "minecraft:blaze_powder"] },
    
    // F
    "minecraft:fermented_spider_eye": { "type": "shapeless", "ingredients": ["minecraft:spider_eye", "minecraft:brown_mushroom", "minecraft:sugar"] },
    "minecraft:fire_charge": { "type": "shapeless", "ingredients": ["minecraft:blaze_powder", "minecraft:coal", "minecraft:gunpowder"] },
    "minecraft:firework_rocket": { "type": "shapeless", "ingredients": ["minecraft:paper", "minecraft:gunpowder"] },
    "minecraft:firework_star": { "type": "shapeless", "ingredients": ["minecraft:gunpowder", "minecraft:red_dye"] }, // Note: Any dye can be used
    "minecraft:fishing_rod": { "type": "shaped", "pattern": ["  S", " S T", "S  T"], "ingredients": { "S": ["minecraft:stick"], "T": ["minecraft:string"] } },
    "minecraft:fletching_table": { "type": "shaped", "pattern": ["FF", "PP", "PP"], "ingredients": { "F": ["minecraft:flint"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:flint_and_steel": { "type": "shapeless", "ingredients": ["minecraft:iron_ingot", "minecraft:flint"] },
    "minecraft:flower_pot": { "type": "shaped", "pattern": ["B B", " B "], "ingredients": { "B": ["minecraft:brick"] } },
    "minecraft:furnace": { "type": "shaped", "pattern": ["CCC", "C C", "CCC"], "ingredients": { "C": RECIPE_VARIANTS.stone_crafting_materials } },
    "minecraft:furnace_minecart": { "type": "shapeless", "ingredients": ["minecraft:furnace", "minecraft:minecart"] },

    // G
    "minecraft:glass": { "type": "furnace", "input": "minecraft:sand" },
    "minecraft:glass_bottle": { "type": "shaped", "pattern": ["G G", " G "], "ingredients": { "G": ["minecraft:glass"] } },
    "minecraft:glass_pane": { "type": "shaped", "pattern": ["GGG", "GGG"], "ingredients": { "G": ["minecraft:glass"] } },
    "minecraft:glistering_melon_slice": { "type": "shaped", "pattern": ["NNN", "NMN", "NNN"], "ingredients": { "N": ["minecraft:gold_nugget"], "M": ["minecraft:melon_slice"] } },
    "minecraft:glow_item_frame": { "type": "shapeless", "ingredients": ["minecraft:item_frame", "minecraft:glow_ink_sac"] },
    "minecraft:glowstone": { "type": "shaped", "pattern": ["DD", "DD"], "ingredients": { "D": ["minecraft:glowstone_dust"] } },
    "minecraft:gold_block": { "type": "shaped", "pattern": ["GGG", "GGG", "GGG"], "ingredients": { "G": ["minecraft:gold_ingot"] } },
    "minecraft:gold_ingot": { "type": "shaped", "pattern": ["NNN", "NNN", "NNN"], "ingredients": { "N": ["minecraft:gold_nugget"] } },
    "minecraft:gold_nugget": { "type": "shapeless", "ingredients": ["minecraft:gold_ingot"] },
    "minecraft:golden_apple": { "type": "shaped", "pattern": ["GGG", "GAG", "GGG"], "ingredients": { "G": ["minecraft:gold_ingot"], "A": ["minecraft:apple"] } },
    "minecraft:golden_axe": { "type": "shaped", "pattern": ["GG ", "GS ", " S "], "ingredients": { "G": ["minecraft:gold_ingot"], "S": ["minecraft:stick"] } },
    "minecraft:golden_boots": { "type": "shaped", "pattern": ["G G", "G G"], "ingredients": { "G": ["minecraft:gold_ingot"] } },
    "minecraft:golden_carrot": { "type": "shaped", "pattern": ["NNN", "NCN", "NNN"], "ingredients": { "N": ["minecraft:gold_nugget"], "C": ["minecraft:carrot"] } },
    "minecraft:golden_chestplate": { "type": "shaped", "pattern": ["G G", "GGG", "GGG"], "ingredients": { "G": ["minecraft:gold_ingot"] } },
    "minecraft:golden_helmet": { "type": "shaped", "pattern": ["GGG", "G G"], "ingredients": { "G": ["minecraft:gold_ingot"] } },
    "minecraft:golden_hoe": { "type": "shaped", "pattern": ["GG", " S", " S"], "ingredients": { "G": ["minecraft:gold_ingot"], "S": ["minecraft:stick"] } },
    "minecraft:golden_leggings": { "type": "shaped", "pattern": ["GGG", "G G", "G G"], "ingredients": { "G": ["minecraft:gold_ingot"] } },
    "minecraft:golden_pickaxe": { "type": "shaped", "pattern": ["GGG", " S ", " S "], "ingredients": { "G": ["minecraft:gold_ingot"], "S": ["minecraft:stick"] } },
    "minecraft:golden_shovel": { "type": "shaped", "pattern": ["G", "S", "S"], "ingredients": { "G": ["minecraft:gold_ingot"], "S": ["minecraft:stick"] } },
    "minecraft:golden_sword": { "type": "shaped", "pattern": ["G", "G", "S"], "ingredients": { "G": ["minecraft:gold_ingot"], "S": ["minecraft:stick"] } },
    "minecraft:granite": { "type": "shapeless", "ingredients": ["minecraft:diorite", "minecraft:quartz"] },
    "minecraft:gray_dye": { "type": "shapeless", "ingredients": ["minecraft:black_dye", "minecraft:white_dye"] },
    "minecraft:green_dye": { "type": "furnace", "input": "minecraft:cactus" },
    "minecraft:grindstone": { "type": "shaped", "pattern": ["SPS", "I I"], "ingredients": { "S": ["minecraft:stick"], "P": ["minecraft:stone_slab"], "I": RECIPE_VARIANTS.planks } },

    // H
    "minecraft:hay_block": { "type": "shaped", "pattern": ["WWW", "WWW", "WWW"], "ingredients": { "W": ["minecraft:wheat"] } },
    "minecraft:heavy_weighted_pressure_plate": { "type": "shaped", "pattern": ["II"], "ingredients": { "I": ["minecraft:iron_ingot"] } },
    "minecraft:hopper": { "type": "shaped", "pattern": ["I I", "ICI", " I "], "ingredients": { "I": ["minecraft:iron_ingot"], "C": ["minecraft:chest"] } },
    "minecraft:hopper_minecart": { "type": "shapeless", "ingredients": ["minecraft:hopper", "minecraft:minecart"] },

    // I
    "minecraft:iron_axe": { "type": "shaped", "pattern": ["II ", "IS ", " S "], "ingredients": { "I": ["minecraft:iron_ingot"], "S": ["minecraft:stick"] } },
    "minecraft:iron_bars": { "type": "shaped", "pattern": ["III", "III"], "ingredients": { "I": ["minecraft:iron_ingot"] } },
    "minecraft:iron_block": { "type": "shaped", "pattern": ["III", "III", "III"], "ingredients": { "I": ["minecraft:iron_ingot"] } },
    "minecraft:iron_boots": { "type": "shaped", "pattern": ["I I", "I I"], "ingredients": { "I": ["minecraft:iron_ingot"] } },
    "minecraft:iron_chestplate": { "type": "shaped", "pattern": ["I I", "III", "III"], "ingredients": { "I": ["minecraft:iron_ingot"] } },
    "minecraft:iron_door": { "type": "shaped", "pattern": ["II", "II", "II"], "ingredients": { "I": ["minecraft:iron_ingot"] } },
    "minecraft:iron_helmet": { "type": "shaped", "pattern": ["III", "I I"], "ingredients": { "I": ["minecraft:iron_ingot"] } },
    "minecraft:iron_hoe": { "type": "shaped", "pattern": ["II", " S", " S"], "ingredients": { "I": ["minecraft:iron_ingot"], "S": ["minecraft:stick"] } },
    "minecraft:iron_ingot": { "type": "shaped", "pattern": ["NNN", "NNN", "NNN"], "ingredients": { "N": ["minecraft:iron_nugget"] } },
    "minecraft:iron_leggings": { "type": "shaped", "pattern": ["III", "I I", "I I"], "ingredients": { "I": ["minecraft:iron_ingot"] } },
    "minecraft:iron_nugget": { "type": "shapeless", "ingredients": ["minecraft:iron_ingot"] },
    "minecraft:iron_pickaxe": { "type": "shaped", "pattern": ["III", " S ", " S "], "ingredients": { "I": ["minecraft:iron_ingot"], "S": ["minecraft:stick"] } },
    "minecraft:iron_shovel": { "type": "shaped", "pattern": ["I", "S", "S"], "ingredients": { "I": ["minecraft:iron_ingot"], "S": ["minecraft:stick"] } },
    "minecraft:iron_sword": { "type": "shaped", "pattern": ["I", "I", "S"], "ingredients": { "I": ["minecraft:iron_ingot"], "S": ["minecraft:stick"] } },
    "minecraft:iron_trapdoor": { "type": "shaped", "pattern": ["II", "II"], "ingredients": { "I": ["minecraft:iron_ingot"] } },
    "minecraft:item_frame": { "type": "shaped", "pattern": ["SSS", "SLS", "SSS"], "ingredients": { "S": ["minecraft:stick"], "L": ["minecraft:leather"] } },

    // J
    "minecraft:jack_o_lantern": { "type": "shapeless", "ingredients": ["minecraft:carved_pumpkin", "minecraft:torch"] },
    "minecraft:jukebox": { "type": "shaped", "pattern": ["PPP", "PDP", "PPP"], "ingredients": { "P": RECIPE_VARIANTS.planks, "D": ["minecraft:diamond"] } },
    "minecraft:jungle_boat": { "type": "shaped", "pattern": ["P P", "PPP"], "ingredients": { "P": ["minecraft:jungle_planks"] } },
    "minecraft:jungle_button": { "type": "shapeless", "ingredients": ["minecraft:jungle_planks"] },
    "minecraft:jungle_chest_boat": { "type": "shapeless", "ingredients": ["minecraft:chest", "minecraft:jungle_boat"] },
    "minecraft:jungle_door": { "type": "shaped", "pattern": ["PP", "PP", "PP"], "ingredients": { "P": ["minecraft:jungle_planks"] } },
    "minecraft:jungle_fence": { "type": "shaped", "pattern": ["PSP", "PSP"], "ingredients": { "P": ["minecraft:jungle_planks"], "S": ["minecraft:stick"] } },
    "minecraft:jungle_fence_gate": { "type": "shaped", "pattern": ["SPS", "SPS"], "ingredients": { "P": ["minecraft:jungle_planks"], "S": ["minecraft:stick"] } },
    "minecraft:jungle_hanging_sign": { "type": "shaped", "pattern": ["C C", "S S"], "ingredients": { "C": ["minecraft:chain"], "S": ["minecraft:stripped_jungle_log"] } },
    "minecraft:jungle_planks": { "type": "shapeless", "ingredients": ["minecraft:jungle_log"] },
    "minecraft:jungle_pressure_plate": { "type": "shaped", "pattern": ["PP"], "ingredients": { "P": ["minecraft:jungle_planks"] } },
    "minecraft:jungle_sign": { "type": "shaped", "pattern": ["PPP", "PPP", " S "], "ingredients": { "P": ["minecraft:jungle_planks"], "S": ["minecraft:stick"] } },
    "minecraft:jungle_slab": { "type": "shaped", "pattern": ["PPP"], "ingredients": { "P": ["minecraft:jungle_planks"] } },
    "minecraft:jungle_stairs": { "type": "shaped", "pattern": ["P  ", "PP ", "PPP"], "ingredients": { "P": ["minecraft:jungle_planks"] } },
    "minecraft:jungle_trapdoor": { "type": "shaped", "pattern": ["PPP", "PPP"], "ingredients": { "P": ["minecraft:jungle_planks"] } },
    "minecraft:jungle_wood": { "type": "shaped", "pattern": ["LL", "LL"], "ingredients": { "L": ["minecraft:jungle_log"] } },
    
    // K
    // knowledge_book is not craftable in survival
    
    // L
    "minecraft:ladder": { "type": "shaped", "pattern": ["S S", "SSS", "S S"], "ingredients": { "S": ["minecraft:stick"] } },
    "minecraft:lantern": { "type": "shaped", "pattern": ["NNN", "NTN", "NNN"], "ingredients": { "N": ["minecraft:iron_nugget"], "T": ["minecraft:torch"] } },
    "minecraft:lapis_block": { "type": "shaped", "pattern": ["LLL", "LLL", "LLL"], "ingredients": { "L": ["minecraft:lapis_lazuli"] } },
    "minecraft:lapis_lazuli": { "type": "shapeless", "ingredients": ["minecraft:lapis_block"] },
    "minecraft:lead": { "type": "shaped", "pattern": ["SS ", "SL ", "  S"], "ingredients": { "S": ["minecraft:string"], "L": ["minecraft:slime_ball"] } },
    "minecraft:leather": { "type": "shaped", "pattern": ["HH", "HH"], "ingredients": { "H": ["minecraft:rabbit_hide"] } },
    "minecraft:leather_boots": { "type": "shaped", "pattern": ["L L", "L L"], "ingredients": { "L": ["minecraft:leather"] } },
    "minecraft:leather_chestplate": { "type": "shaped", "pattern": ["L L", "LLL", "LLL"], "ingredients": { "L": ["minecraft:leather"] } },
    "minecraft:leather_helmet": { "type": "shaped", "pattern": ["LLL", "L L"], "ingredients": { "L": ["minecraft:leather"] } },
    "minecraft:leather_horse_armor": { "type": "shaped", "pattern": ["L L", "LLL", "L L"], "ingredients": { "L": ["minecraft:leather"] } },
    "minecraft:leather_leggings": { "type": "shaped", "pattern": ["LLL", "L L", "L L"], "ingredients": { "L": ["minecraft:leather"] } },
    "minecraft:lectern": { "type": "shaped", "pattern": ["SSS", " B ", " S "], "ingredients": { "S": ["minecraft:oak_slab", "minecraft:spruce_slab", "minecraft:birch_slab", "minecraft:jungle_slab", "minecraft:acacia_slab", "minecraft:dark_oak_slab"], "B": ["minecraft:bookshelf"] } },
    "minecraft:lever": { "type": "shaped", "pattern": ["S", "C"], "ingredients": { "S": ["minecraft:stick"], "C": ["minecraft:cobblestone"] } },
    "minecraft:light_blue_dye": { "type": "shapeless", "ingredients": ["minecraft:blue_dye", "minecraft:white_dye"] },
    "minecraft:light_gray_dye": { "type": "shapeless", "ingredients": ["minecraft:gray_dye", "minecraft:white_dye"] },
    "minecraft:light_weighted_pressure_plate": { "type": "shaped", "pattern": ["GG"], "ingredients": { "G": ["minecraft:gold_ingot"] } },
    "minecraft:lightning_rod": { "type": "shaped", "pattern": ["C", "C", "C"], "ingredients": { "C": ["minecraft:copper_ingot"] } },
    "minecraft:lime_dye": { "type": "shapeless", "ingredients": ["minecraft:green_dye", "minecraft:white_dye"] },
    "minecraft:lodestone": { "type": "shaped", "pattern": ["SSS", "SNS", "SSS"], "ingredients": { "S": ["minecraft:chiseled_stone_bricks"], "N": ["minecraft:netherite_ingot"] } },
    "minecraft:loom": { "type": "shaped", "pattern": ["SS", "PP"], "ingredients": { "S": ["minecraft:string"], "P": RECIPE_VARIANTS.planks } },

    // M
    "minecraft:mace": { "type": "shaped", "pattern": [" B ", " R "], "ingredients": { "B": ["minecraft:heavy_core"], "R": ["minecraft:breeze_rod"] } },
    "minecraft:magenta_dye": { "type": "shapeless", "ingredients": ["minecraft:purple_dye", "minecraft:pink_dye"] },
    "minecraft:magma_block": { "type": "shaped", "pattern": ["MM", "MM"], "ingredients": { "M": ["minecraft:magma_cream"] } },
    "minecraft:magma_cream": { "type": "shapeless", "ingredients": ["minecraft:blaze_powder", "minecraft:slime_ball"] },
    "minecraft:mangrove_boat": { "type": "shaped", "pattern": ["P P", "PPP"], "ingredients": { "P": ["minecraft:mangrove_planks"] } },
    "minecraft:mangrove_button": { "type": "shapeless", "ingredients": ["minecraft:mangrove_planks"] },
    "minecraft:mangrove_chest_boat": { "type": "shapeless", "ingredients": ["minecraft:chest", "minecraft:mangrove_boat"] },
    "minecraft:mangrove_door": { "type": "shaped", "pattern": ["PP", "PP", "PP"], "ingredients": { "P": ["minecraft:mangrove_planks"] } },
    "minecraft:mangrove_fence": { "type": "shaped", "pattern": ["PSP", "PSP"], "ingredients": { "P": ["minecraft:mangrove_planks"], "S": ["minecraft:stick"] } },
    "minecraft:mangrove_fence_gate": { "type": "shaped", "pattern": ["SPS", "SPS"], "ingredients": { "P": ["minecraft:mangrove_planks"], "S": ["minecraft:stick"] } },
    "minecraft:mangrove_hanging_sign": { "type": "shaped", "pattern": ["C C", "S S"], "ingredients": { "C": ["minecraft:chain"], "S": ["minecraft:stripped_mangrove_log"] } },
    "minecraft:mangrove_planks": { "type": "shapeless", "ingredients": ["minecraft:mangrove_log"] },
    "minecraft:mangrove_pressure_plate": { "type": "shaped", "pattern": ["PP"], "ingredients": { "P": ["minecraft:mangrove_planks"] } },
    "minecraft:mangrove_sign": { "type": "shaped", "pattern": ["PPP", "PPP", " S "], "ingredients": { "P": ["minecraft:mangrove_planks"], "S": ["minecraft:stick"] } },
    "minecraft:mangrove_slab": { "type": "shaped", "pattern": ["PPP"], "ingredients": { "P": ["minecraft:mangrove_planks"] } },
    "minecraft:mangrove_stairs": { "type": "shaped", "pattern": ["P  ", "PP ", "PPP"], "ingredients": { "P": ["minecraft:mangrove_planks"] } },
    "minecraft:mangrove_trapdoor": { "type": "shaped", "pattern": ["PPP", "PPP"], "ingredients": { "P": ["minecraft:mangrove_planks"] } },
    "minecraft:mangrove_wood": { "type": "shaped", "pattern": ["LL", "LL"], "ingredients": { "L": ["minecraft:mangrove_log"] } },
    "minecraft:map": { "type": "shaped", "pattern": ["PPP", "PCP", "PPP"], "ingredients": { "P": ["minecraft:paper"], "C": ["minecraft:compass"] } },
    "minecraft:melon": { "type": "shaped", "pattern": ["SSS", "SSS", "SSS"], "ingredients": { "S": ["minecraft:melon_slice"] } },
    "minecraft:melon_seeds": { "type": "shapeless", "ingredients": ["minecraft:melon_slice"] },
    "minecraft:minecart": { "type": "shaped", "pattern": ["I I", "III"], "ingredients": { "I": ["minecraft:iron_ingot"] } },
    "minecraft:moss_carpet": { "type": "shaped", "pattern": ["MM"], "ingredients": { "M": ["minecraft:moss_block"] } },
    "minecraft:mossy_cobblestone": { "type": "shapeless", "ingredients": ["minecraft:cobblestone", "minecraft:vine"] },
    "minecraft:mossy_cobblestone_slab": { "type": "shaped", "pattern": ["CCC"], "ingredients": { "C": ["minecraft:mossy_cobblestone"] } },
    "minecraft:mossy_cobblestone_stairs": { "type": "shaped", "pattern": ["C  ", "CC ", "CCC"], "ingredients": { "C": ["minecraft:mossy_cobblestone"] } },
    "minecraft:mossy_cobblestone_wall": { "type": "shaped", "pattern": ["CCC", "CCC"], "ingredients": { "C": ["minecraft:mossy_cobblestone"] } },
    "minecraft:mossy_stone_brick_slab": { "type": "shaped", "pattern": ["BBB"], "ingredients": { "B": ["minecraft:mossy_stone_bricks"] } },
    "minecraft:mossy_stone_brick_stairs": { "type": "shaped", "pattern": ["B  ", "BB ", "BBB"], "ingredients": { "B": ["minecraft:mossy_stone_bricks"] } },
    "minecraft:mossy_stone_brick_wall": { "type": "shaped", "pattern": ["BBB", "BBB"], "ingredients": { "B": ["minecraft:mossy_stone_bricks"] } },
    "minecraft:mossy_stone_bricks": { "type": "shapeless", "ingredients": ["minecraft:stone_bricks", "minecraft:vine"] },
    "minecraft:mud_bricks": { "type": "shaped", "pattern": ["MM", "MM"], "ingredients": { "M": ["minecraft:packed_mud"] } },
    "minecraft:mushroom_stew": { "type": "shapeless", "ingredients": ["minecraft:bowl", "minecraft:red_mushroom", "minecraft:brown_mushroom"] },
    "minecraft:music_disc_5": { "type": "shaped", "pattern": [" F ", "FFF", " F "], "ingredients": { "F": ["minecraft:disc_fragment_5"] } },

    // N
    "minecraft:nether_brick": { "type": "furnace", "input": "minecraft:netherrack" },
    "minecraft:nether_brick_fence": { "type": "shaped", "pattern": ["NBN", "NBN"], "ingredients": { "N": ["minecraft:nether_brick"], "B": ["minecraft:nether_bricks"] } },
    "minecraft:nether_brick_slab": { "type": "shaped", "pattern": ["BBB"], "ingredients": { "B": ["minecraft:nether_bricks"] } },
    "minecraft:nether_brick_stairs": { "type": "shaped", "pattern": ["B  ", "BB ", "BBB"], "ingredients": { "B": ["minecraft:nether_bricks"] } },
    "minecraft:nether_brick_wall": { "type": "shaped", "pattern": ["BBB", "BBB"], "ingredients": { "B": ["minecraft:nether_bricks"] } },
    "minecraft:nether_bricks": { "type": "shaped", "pattern": ["BB", "BB"], "ingredients": { "B": ["minecraft:nether_brick"] } },
    "minecraft:netherite_block": { "type": "shaped", "pattern": ["NNN", "NNN", "NNN"], "ingredients": { "N": ["minecraft:netherite_ingot"] } },
    "minecraft:netherite_ingot": { "type": "shapeless", "ingredients": ["minecraft:netherite_scrap", "minecraft:netherite_scrap", "minecraft:netherite_scrap", "minecraft:netherite_scrap", "minecraft:gold_ingot", "minecraft:gold_ingot", "minecraft:gold_ingot", "minecraft:gold_ingot"] },
    "minecraft:netherite_scrap": { "type": "furnace", "input": "minecraft:ancient_debris" },
    "minecraft:note_block": { "type": "shaped", "pattern": ["PPP", "PRP", "PPP"], "ingredients": { "P": RECIPE_VARIANTS.planks, "R": ["minecraft:redstone"] } },

    // O
    "minecraft:observer": { "type": "shaped", "pattern": ["CCC", "RRQ", "CCC"], "ingredients": { "C": ["minecraft:cobblestone"], "R": ["minecraft:redstone"], "Q": ["minecraft:quartz"] } },
    "minecraft:orange_dye": { "type": "shapeless", "ingredients": ["minecraft:red_dye", "minecraft:yellow_dye"] },

    // P
    "minecraft:packed_ice": { "type": "shaped", "pattern": ["III", "III", "III"], "ingredients": { "I": ["minecraft:ice"] } },
    "minecraft:packed_mud": { "type": "shapeless", "ingredients": ["minecraft:mud", "minecraft:wheat"] },
    "minecraft:painting": { "type": "shaped", "pattern": ["SSS", "SWS", "SSS"], "ingredients": { "S": ["minecraft:stick"], "W": RECIPE_VARIANTS.wool } },
    "minecraft:paper": { "type": "shaped", "pattern": ["SSS"], "ingredients": { "S": ["minecraft:sugar_cane"] } },
    "minecraft:pink_dye": { "type": "shapeless", "ingredients": ["minecraft:red_dye", "minecraft:white_dye"] },
    "minecraft:piston": { "type": "shaped", "pattern": ["PPP", "CIC", "CRC"], "ingredients": { "P": RECIPE_VARIANTS.planks, "C": ["minecraft:cobblestone"], "I": ["minecraft:iron_ingot"], "R": ["minecraft:redstone"] } },
    "minecraft:pumpkin_pie": { "type": "shapeless", "ingredients": ["minecraft:pumpkin", "minecraft:sugar", "minecraft:egg"] },
    "minecraft:pumpkin_seeds": { "type": "shapeless", "ingredients": ["minecraft:pumpkin"] },
    "minecraft:purple_dye": { "type": "shapeless", "ingredients": ["minecraft:red_dye", "minecraft:blue_dye"] },
    "minecraft:purpur_block": { "type": "shaped", "pattern": ["CC", "CC"], "ingredients": { "C": ["minecraft:popped_chorus_fruit"] } },
    "minecraft:purpur_pillar": { "type": "shaped", "pattern": ["S", "S"], "ingredients": { "S": ["minecraft:purpur_slab"] } },
    "minecraft:purpur_slab": { "type": "shaped", "pattern": ["BBB"], "ingredients": { "B": ["minecraft:purpur_block"] } },
    "minecraft:purpur_stairs": { "type": "shaped", "pattern": ["B  ", "BB ", "BBB"], "ingredients": { "B": ["minecraft:purpur_block"] } },

    // Q
    "minecraft:quartz_block": { "type": "shaped", "pattern": ["QQ", "QQ"], "ingredients": { "Q": ["minecraft:quartz"] } },
    "minecraft:quartz_bricks": { "type": "shaped", "pattern": ["QQ", "QQ"], "ingredients": { "Q": ["minecraft:quartz_block"] } },
    "minecraft:quartz_pillar": { "type": "shaped", "pattern": ["Q", "Q"], "ingredients": { "Q": ["minecraft:quartz_block"] } },
    "minecraft:quartz_slab": { "type": "shaped", "pattern": ["QQQ"], "ingredients": { "Q": ["minecraft:quartz_block"] } },
    "minecraft:quartz_stairs": { "type": "shaped", "pattern": ["Q  ", "QQ ", "QQQ"], "ingredients": { "Q": ["minecraft:quartz_block"] } },
    
    // R
    "minecraft:rabbit_stew": { "type": "shaped", "pattern": [" R ", "PKB", " V "], "ingredients": { "R": ["minecraft:cooked_rabbit"], "P": ["minecraft:baked_potato"], "K": ["minecraft:carrot"], "B": ["minecraft:brown_mushroom"], "V": ["minecraft:bowl"] } },
    "minecraft:rail": { "type": "shaped", "pattern": ["I I", "ISI", "I I"], "ingredients": { "I": ["minecraft:iron_ingot"], "S": ["minecraft:stick"] } },
    "minecraft:red_dye": { "type": "shapeless", "ingredients": ["minecraft:poppy"] },
    "minecraft:red_nether_bricks": { "type": "shaped", "pattern": ["NB", "BN"], "ingredients": { "N": ["minecraft:nether_wart"], "B": ["minecraft:nether_brick"] } },
    "minecraft:red_sandstone": { "type": "shaped", "pattern": ["SS", "SS"], "ingredients": { "S": ["minecraft:red_sand"] } },
    "minecraft:redstone_block": { "type": "shaped", "pattern": ["RRR", "RRR", "RRR"], "ingredients": { "R": ["minecraft:redstone"] } },
    "minecraft:redstone_lamp": { "type": "shaped", "pattern": [" R ", "RGR", " R "], "ingredients": { "R": ["minecraft:redstone"], "G": ["minecraft:glowstone"] } },
    "minecraft:repeater": { "type": "shaped", "pattern": ["TRT", "SSS"], "ingredients": { "T": ["minecraft:redstone_torch"], "R": ["minecraft:redstone"], "S": ["minecraft:stone"] } },
    "minecraft:respawn_anchor": { "type": "shaped", "pattern": ["OOO", "GGG", "OOO"], "ingredients": { "O": ["minecraft:crying_obsidian"], "G": ["minecraft:glowstone"] } },
    "minecraft:rooted_dirt": { "type": "shapeless", "ingredients": ["minecraft:dirt", "minecraft:hanging_roots"] },
    
    // S
    "minecraft:sandstone": { "type": "shaped", "pattern": ["SS", "SS"], "ingredients": { "S": ["minecraft:sand"] } },
    "minecraft:scaffolding": { "type": "shaped", "pattern": ["BSB", "B B", "B B"], "ingredients": { "B": ["minecraft:bamboo"], "S": ["minecraft:string"] } },
    "minecraft:sea_lantern": { "type": "shaped", "pattern": ["CCC", "CSC", "CCC"], "ingredients": { "C": ["minecraft:prismarine_crystals"], "S": ["minecraft:prismarine_shard"] } },
    "minecraft:shears": { "type": "shaped", "pattern": [" I", "I "], "ingredients": { "I": ["minecraft:iron_ingot"] } },
    "minecraft:shield": { "type": "shaped", "pattern": ["PIP", "PPP", " P "], "ingredients": { "P": RECIPE_VARIANTS.planks, "I": ["minecraft:iron_ingot"] } },
    "minecraft:shulker_box": { "type": "shaped", "pattern": ["S", "C", "S"], "ingredients": { "S": ["minecraft:shulker_shell"], "C": ["minecraft:chest"] } },
    "minecraft:slime_block": { "type": "shaped", "pattern": ["SSS", "SSS", "SSS"], "ingredients": { "S": ["minecraft:slime_ball"] } },
    "minecraft:smithing_table": { "type": "shaped", "pattern": ["II", "PP", "PP"], "ingredients": { "I": ["minecraft:iron_ingot"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:smoker": { "type": "shaped", "pattern": [" L ", "LFL", " L "], "ingredients": { "F": ["minecraft:furnace"], "L": RECIPE_VARIANTS.logs } },
    "minecraft:smooth_stone": { "type": "furnace", "input": "minecraft:stone" },
    "minecraft:snow_block": { "type": "shaped", "pattern": ["SS", "SS"], "ingredients": { "S": ["minecraft:snowball"] } },
    "minecraft:soul_campfire": { "type": "shaped", "pattern": [" S ", "SCS", "LLL"], "ingredients": { "S": ["minecraft:stick"], "C": ["minecraft:soul_sand", "minecraft:soul_soil"], "L": RECIPE_VARIANTS.logs } },
    "minecraft:soul_lantern": { "type": "shaped", "pattern": ["NNN", "NTN", "NNN"], "ingredients": { "N": ["minecraft:iron_nugget"], "T": ["minecraft:soul_torch"] } },
    "minecraft:soul_torch": { "type": "shaped", "pattern": ["C", "S", "L"], "ingredients": { "C": ["minecraft:coal", "minecraft:charcoal"], "S": ["minecraft:stick"], "L": ["minecraft:soul_sand", "minecraft:soul_soil"] } },
    "minecraft:spectral_arrow": { "type": "shaped", "pattern": ["G", "A"], "ingredients": { "G": ["minecraft:glowstone_dust"], "A": ["minecraft:arrow"] } },
    "minecraft:spyglass": { "type": "shaped", "pattern": ["A", "C", "C"], "ingredients": { "A": ["minecraft:amethyst_shard"], "C": ["minecraft:copper_ingot"] } },
    "minecraft:stick": { "type": "shaped", "pattern": ["P", "P"], "ingredients": { "P": RECIPE_VARIANTS.planks } },
    "minecraft:sticky_piston": { "type": "shapeless", "ingredients": ["minecraft:piston", "minecraft:slime_ball"] },
    "minecraft:stone_axe": { "type": "shaped", "pattern": ["CC ", "CS ", " S "], "ingredients": { "C": RECIPE_VARIANTS.stone_crafting_materials, "S": ["minecraft:stick"] } },
    "minecraft:stone_hoe": { "type": "shaped", "pattern": ["CC", " S", " S"], "ingredients": { "C": RECIPE_VARIANTS.stone_crafting_materials, "S": ["minecraft:stick"] } },
    "minecraft:stone_pickaxe": { "type": "shaped", "pattern": ["CCC", " S ", " S "], "ingredients": { "C": RECIPE_VARIANTS.stone_crafting_materials, "S": ["minecraft:stick"] } },
    "minecraft:stone_shovel": { "type": "shaped", "pattern": ["C", "S", "S"], "ingredients": { "C": RECIPE_VARIANTS.stone_crafting_materials, "S": ["minecraft:stick"] } },
    "minecraft:stone_sword": { "type": "shaped", "pattern": ["C", "C", "S"], "ingredients": { "C": RECIPE_VARIANTS.stone_crafting_materials, "S": ["minecraft:stick"] } },
    "minecraft:stonecutter": { "type": "shaped", "pattern": [" I ", "SSS"], "ingredients": { "I": ["minecraft:iron_ingot"], "S": ["minecraft:stone"] } },
    "minecraft:sugar": { "type": "shapeless", "ingredients": ["minecraft:sugar_cane"] },
    "minecraft:suspicious_stew": { "type": "shapeless", "ingredients": ["minecraft:bowl", "minecraft:red_mushroom", "minecraft:brown_mushroom", "minecraft:poppy"] },
    
    // T
    "minecraft:target": { "type": "shaped", "pattern": [" R ", "RHR", " R "], "ingredients": { "R": ["minecraft:redstone"], "H": ["minecraft:hay_block"] } },
    "minecraft:tnt": { "type": "shaped", "pattern": ["SGS", "GSG", "SGS"], "ingredients": { "S": ["minecraft:sand", "minecraft:red_sand"], "G": ["minecraft:gunpowder"] } },
    "minecraft:tnt_minecart": { "type": "shapeless", "ingredients": ["minecraft:tnt", "minecraft:minecart"] },
    "minecraft:torch": { "type": "shaped", "pattern": ["C", "S"], "ingredients": { "C": ["minecraft:coal", "minecraft:charcoal"], "S": ["minecraft:stick"] } },
    "minecraft:trapped_chest": { "type": "shapeless", "ingredients": ["minecraft:chest", "minecraft:tripwire_hook"] },
    "minecraft:tripwire_hook": { "type": "shaped", "pattern": ["I", "S", "P"], "ingredients": { "I": ["minecraft:iron_ingot"], "S": ["minecraft:stick"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:turtle_helmet": { "type": "shaped", "pattern": ["SSS", "S S"], "ingredients": { "S": ["minecraft:scute"] } },
    
    // W
    "minecraft:warped_button": { "type": "shapeless", "ingredients": ["minecraft:warped_planks"] },
    "minecraft:warped_door": { "type": "shaped", "pattern": ["PP", "PP", "PP"], "ingredients": { "P": ["minecraft:warped_planks"] } },
    "minecraft:warped_fence": { "type": "shaped", "pattern": ["PSP", "PSP"], "ingredients": { "P": ["minecraft:warped_planks"], "S": ["minecraft:stick"] } },
    "minecraft:warped_fence_gate": { "type": "shaped", "pattern": ["SPS", "SPS"], "ingredients": { "P": ["minecraft:warped_planks"], "S": ["minecraft:stick"] } },
    "minecraft:warped_fungus_on_a_stick": { "type": "shapeless", "ingredients": ["minecraft:fishing_rod", "minecraft:warped_fungus"] },
    "minecraft:warped_hanging_sign": { "type": "shaped", "pattern": ["C C", "S S"], "ingredients": { "C": ["minecraft:chain"], "S": ["minecraft:stripped_warped_stem"] } },
    "minecraft:warped_pressure_plate": { "type": "shaped", "pattern": ["PP"], "ingredients": { "P": ["minecraft:warped_planks"] } },
    "minecraft:warped_sign": { "type": "shaped", "pattern": ["PPP", "PPP", " S "], "ingredients": { "P": ["minecraft:warped_planks"], "S": ["minecraft:stick"] } },
    "minecraft:warped_slab": { "type": "shaped", "pattern": ["PPP"], "ingredients": { "P": ["minecraft:warped_planks"] } },
    "minecraft:warped_stairs": { "type": "shaped", "pattern": ["P  ", "PP ", "PPP"], "ingredients": { "P": ["minecraft:warped_planks"] } },
    "minecraft:warped_trapdoor": { "type": "shaped", "pattern": ["PPP", "PPP"], "ingredients": { "P": ["minecraft:warped_planks"] } },
    "minecraft:warped_wart_block": { "type": "shaped", "pattern": ["FFF", "FFF", "FFF"], "ingredients": { "F": ["minecraft:warped_fungus"] } },
    "minecraft:weathered_chiseled_copper": { "type": "shaped", "pattern": ["S", "S"], "ingredients": { "S": ["minecraft:weathered_cut_copper_slab"] } },
    "minecraft:weathered_cut_copper": { "type": "shaped", "pattern": ["CC", "CC"], "ingredients": { "C": ["minecraft:weathered_copper"] } },
    "minecraft:weathered_cut_copper_slab": { "type": "shaped", "pattern": ["CCC"], "ingredients": { "C": ["minecraft:weathered_cut_copper"] } },
    "minecraft:weathered_cut_copper_stairs": { "type": "shaped", "pattern": ["C  ", "CC ", "CCC"], "ingredients": { "C": ["minecraft:weathered_cut_copper"] } },
    "minecraft:white_dye": { "type": "shapeless", "ingredients": ["minecraft:bone_meal", "minecraft:lily_of_the_valley"] },
    "minecraft:wolf_armor": { "type": "shaped", "pattern": ["S S", "SSS", " S "], "ingredients": { "S": ["minecraft:armadillo_scute"] } },
    "minecraft:wooden_axe": { "type": "shaped", "pattern": ["PP ", "PS ", " S "], "ingredients": { "P": RECIPE_VARIANTS.planks, "S": ["minecraft:stick"] } },
    "minecraft:wooden_hoe": { "type": "shaped", "pattern": ["PP", " S", " S"], "ingredients": { "P": RECIPE_VARIANTS.planks, "S": ["minecraft:stick"] } },
    "minecraft:wooden_pickaxe": { "type": "shaped", "pattern": ["PPP", " S ", " S "], "ingredients": { "P": RECIPE_VARIANTS.planks, "S": ["minecraft:stick"] } },
    "minecraft:wooden_shovel": { "type": "shaped", "pattern": ["P", "S", "S"], "ingredients": { "P": RECIPE_VARIANTS.planks, "S": ["minecraft:stick"] } },
    "minecraft:wooden_sword": { "type": "shaped", "pattern": ["P", "P", "S"], "ingredients": { "P": RECIPE_VARIANTS.planks, "S": ["minecraft:stick"] } },
    "minecraft:writable_book": { "type": "shapeless", "ingredients": ["minecraft:book", "minecraft:ink_sac", "minecraft:feather"] },
    "minecraft:yellow_dye": { "type": "shapeless", "ingredients": ["minecraft:sunflower", "minecraft:dandelion"] },
    
    // --- Variantes de couleur ---
    // Lits
    "minecraft:orange_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:orange_wool"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:magenta_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:magenta_wool"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:light_blue_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:light_blue_wool"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:yellow_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:yellow_wool"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:lime_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:lime_wool"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:pink_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:pink_wool"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:gray_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:gray_wool"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:light_gray_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:light_gray_wool"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:cyan_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:cyan_wool"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:purple_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:purple_wool"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:blue_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:blue_wool"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:brown_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:brown_wool"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:green_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:green_wool"], "P": RECIPE_VARIANTS.planks } },
    "minecraft:red_bed": { "type": "shaped", "pattern": ["WWW", "PPP"], "ingredients": { "W": ["minecraft:red_wool"], "P": RECIPE_VARIANTS.planks } },

    // Laine
    "minecraft:white_wool": { "type": "shaped", "pattern": ["SS", "SS"], "ingredients": { "S": ["minecraft:string"] } },
    "minecraft:orange_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:orange_dye"] },
    "minecraft:magenta_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:magenta_dye"] },
    "minecraft:light_blue_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:light_blue_dye"] },
    "minecraft:yellow_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:yellow_dye"] },
    "minecraft:lime_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:lime_dye"] },
    "minecraft:pink_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:pink_dye"] },
    "minecraft:gray_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:gray_dye"] },
    "minecraft:light_gray_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:light_gray_dye"] },
    "minecraft:cyan_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:cyan_dye"] },
    "minecraft:purple_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:purple_dye"] },
    "minecraft:blue_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:blue_dye"] },
    "minecraft:brown_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:brown_dye"] },
    "minecraft:green_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:green_dye"] },
    "minecraft:red_wool": { "type": "shapeless", "ingredients": ["minecraft:white_wool", "minecraft:red_dye"] }
};